import { initializeApp } from "firebase-admin/app";
import { getFirestore, FieldValue, Timestamp } from "firebase-admin/firestore";
import { onCall, HttpsError } from "firebase-functions/v2/https";
import { defineSecret } from "firebase-functions/params";

initializeApp();
const db=getFirestore();
const mapsServerKey=defineSecret("GOOGLE_MAPS_SERVER_KEY");
const REGION="europe-west1";
const MAX_PLAYERS=8;
const LOCATION_POOL=[
  {lat:60.1699,lng:24.9384,city:"Helsinki",country:"Finland"},{lat:59.3293,lng:18.0686,city:"Stockholm",country:"Sweden"},{lat:55.6761,lng:12.5683,city:"Copenhagen",country:"Denmark"},{lat:52.52,lng:13.405,city:"Berlin",country:"Germany"},{lat:48.8566,lng:2.3522,city:"Paris",country:"France"},{lat:41.9028,lng:12.4964,city:"Rome",country:"Italy"},{lat:38.7223,lng:-9.1393,city:"Lisbon",country:"Portugal"},{lat:40.4168,lng:-3.7038,city:"Madrid",country:"Spain"},{lat:51.5074,lng:-.1278,city:"London",country:"United Kingdom"},{lat:53.3498,lng:-6.2603,city:"Dublin",country:"Ireland"},{lat:50.0755,lng:14.4378,city:"Prague",country:"Czechia"},{lat:47.4979,lng:19.0402,city:"Budapest",country:"Hungary"},{lat:37.9838,lng:23.7275,city:"Athens",country:"Greece"},{lat:35.6762,lng:139.6503,city:"Tokyo",country:"Japan"},{lat:34.6937,lng:135.5023,city:"Osaka",country:"Japan"},{lat:37.5665,lng:126.978,city:"Seoul",country:"South Korea"},{lat:1.3521,lng:103.8198,city:"Singapore",country:"Singapore"},{lat:13.7563,lng:100.5018,city:"Bangkok",country:"Thailand"},{lat:-33.8688,lng:151.2093,city:"Sydney",country:"Australia"},{lat:-37.8136,lng:144.9631,city:"Melbourne",country:"Australia"},{lat:-36.8485,lng:174.7633,city:"Auckland",country:"New Zealand"},{lat:40.7128,lng:-74.006,city:"New York",country:"United States"},{lat:34.0522,lng:-118.2437,city:"Los Angeles",country:"United States"},{lat:41.8781,lng:-87.6298,city:"Chicago",country:"United States"},{lat:49.2827,lng:-123.1207,city:"Vancouver",country:"Canada"},{lat:43.6532,lng:-79.3832,city:"Toronto",country:"Canada"},{lat:19.4326,lng:-99.1332,city:"Mexico City",country:"Mexico"},{lat:-23.5505,lng:-46.6333,city:"São Paulo",country:"Brazil"},{lat:-34.6037,lng:-58.3816,city:"Buenos Aires",country:"Argentina"},{lat:-33.4489,lng:-70.6693,city:"Santiago",country:"Chile"},{lat:-33.9249,lng:18.4241,city:"Cape Town",country:"South Africa"},{lat:-1.2921,lng:36.8219,city:"Nairobi",country:"Kenya"},{lat:25.2048,lng:55.2708,city:"Dubai",country:"United Arab Emirates"},{lat:31.7683,lng:35.2137,city:"Jerusalem",country:"Israel"}
];

const options={region:REGION,cors:true,secrets:[mapsServerKey],timeoutSeconds:30,memory:"256MiB"};
function requireAuth(request){ if(!request.auth)throw new HttpsError("unauthenticated","Sign in first.");return request.auth.uid; }
function cleanCode(code){ return String(code||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6); }
function randomCode(){ const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join(""); }
function shuffle(items){ const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy; }
function haversine(a,b){ const r=6371,toRad=(v)=>v*Math.PI/180;const dLat=toRad(b.lat-a.lat),dLng=toRad(b.lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x)); }
function scoreFor(distanceKm){ return Math.max(0,Math.round(5000*Math.exp(-distanceKm/2000))); }
async function userProfile(uid){ const snap=await db.doc(`users/${uid}`).get();if(!snap.exists)throw new HttpsError("failed-precondition","Player profile is missing.");return snap.data(); }
async function assertMember(code,uid){ const snap=await db.doc(`rooms/${code}/players/${uid}`).get();if(!snap.exists)throw new HttpsError("permission-denied","You are not in this room.");return snap.data(); }
async function roomAndPrivate(code){ const [roomSnap,privateSnap]=await Promise.all([db.doc(`rooms/${code}`).get(),db.doc(`rooms/${code}/private/game`).get()]);if(!roomSnap.exists||!privateSnap.exists)throw new HttpsError("not-found","Room not found.");return {room:roomSnap.data(),game:privateSnap.data()}; }
async function panoFor(location){ const key=mapsServerKey.value();if(!key)throw new HttpsError("failed-precondition","GOOGLE_MAPS_SERVER_KEY is not configured.");const url=new URL("https://maps.googleapis.com/maps/api/streetview/metadata");url.searchParams.set("location",`${location.lat},${location.lng}`);url.searchParams.set("radius","2500");url.searchParams.set("source","outdoor");url.searchParams.set("key",key);const response=await fetch(url);const data=await response.json();if(data.status!=="OK"||!data.pano_id)throw new HttpsError("not-found",`No Street View panorama near ${location.city}.`);return data.pano_id; }
async function prepareRound(code,room,game,roundNumber){ const location=game.locations[roundNumber-1];const panoId=await panoFor(location);const start=Timestamp.now();const end=Timestamp.fromMillis(start.toMillis()+room.roundSeconds*1000);await db.doc(`rooms/${code}`).update({status:"playing",phase:"guessing",currentRound:roundNumber,currentPanoId:panoId,roundStartedAt:start,roundEndsAt:end,revealedLocation:FieldValue.delete(),roundResults:{},updatedAt:FieldValue.serverTimestamp()});const players=await db.collection(`rooms/${code}/players`).get();const batch=db.batch();players.forEach((snap)=>batch.update(snap.ref,{hasGuessedCurrentRound:false,lastRoundScore:0}));await batch.commit(); }

export const createRoom=onCall(options,async(request)=>{ const uid=requireAuth(request);const profile=await userProfile(uid);let code;for(let i=0;i<8;i++){const candidate=randomCode();if(!(await db.doc(`rooms/${candidate}`).get()).exists){code=candidate;break;}}if(!code)throw new HttpsError("resource-exhausted","Could not create room code.");const roundCount=Math.min(10,Math.max(3,Number(request.data?.roundCount)||5));const roundSeconds=[60,90,120].includes(Number(request.data?.roundSeconds))?Number(request.data.roundSeconds):90;const locations=shuffle(LOCATION_POOL).slice(0,roundCount);const now=FieldValue.serverTimestamp();const batch=db.batch();batch.set(db.doc(`rooms/${code}`),{hostUid:uid,status:"lobby",phase:"lobby",roundCount,roundSeconds,currentRound:0,maxPlayers:MAX_PLAYERS,createdAt:now,updatedAt:now});batch.set(db.doc(`rooms/${code}/private/game`),{locations,createdAt:now});batch.set(db.doc(`rooms/${code}/players/${uid}`),{displayName:profile.displayName||"Explorer",photoURL:profile.photoURL||"",ready:Boolean(request.data?.solo),totalScore:0,lastRoundScore:0,hasGuessedCurrentRound:false,joinedAt:now});await batch.commit();return {roomCode:code}; });

export const joinRoom=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);const profile=await userProfile(uid);const roomRef=db.doc(`rooms/${code}`);await db.runTransaction(async(tx)=>{const roomSnap=await tx.get(roomRef);if(!roomSnap.exists)throw new HttpsError("not-found","Room not found.");const room=roomSnap.data();if(room.status!=="lobby")throw new HttpsError("failed-precondition","The match has already started.");const players=await db.collection(`rooms/${code}/players`).count().get();if(players.data().count>=MAX_PLAYERS)throw new HttpsError("resource-exhausted","Room is full.");tx.set(db.doc(`rooms/${code}/players/${uid}`),{displayName:profile.displayName||"Explorer",photoURL:profile.photoURL||"",ready:false,totalScore:0,lastRoundScore:0,hasGuessedCurrentRound:false,joinedAt:FieldValue.serverTimestamp()},{merge:true});});return {roomCode:code}; });

export const toggleReady=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);const ref=db.doc(`rooms/${code}/players/${uid}`);await db.runTransaction(async(tx)=>{const snap=await tx.get(ref);if(!snap.exists)throw new HttpsError("not-found","Player not found.");tx.update(ref,{ready:!snap.data().ready});});return {ok:true}; });

export const startGame=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);await assertMember(code,uid);const {room,game}=await roomAndPrivate(code);if(room.hostUid!==uid)throw new HttpsError("permission-denied","Only the host can start.");if(room.status!=="lobby")throw new HttpsError("failed-precondition","Match already started.");const roundCount=Math.min(game.locations.length,Math.max(3,Number(request.data?.roundCount)||room.roundCount));const roundSeconds=[60,90,120].includes(Number(request.data?.roundSeconds))?Number(request.data.roundSeconds):room.roundSeconds;await db.doc(`rooms/${code}`).update({roundCount,roundSeconds});await prepareRound(code,{...room,roundCount,roundSeconds},game,1);return {ok:true}; });

export const submitGuess=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);await assertMember(code,uid);const {room,game}=await roomAndPrivate(code);const round=Number(request.data?.round);if(room.status!=="playing"||room.phase!=="guessing"||round!==room.currentRound)throw new HttpsError("failed-precondition","Round is not accepting guesses.");if(room.roundEndsAt.toMillis()+2000<Date.now())throw new HttpsError("deadline-exceeded","Round time has expired.");const lat=Number(request.data?.lat),lng=Number(request.data?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<-90||lat>90||lng<-180||lng>180)throw new HttpsError("invalid-argument","Invalid map coordinates.");const location=game.locations[round-1];const distanceKm=haversine({lat,lng},location);const score=scoreFor(distanceKm);const guessRef=db.doc(`rooms/${code}/rounds/${round}/guesses/${uid}`);const playerRef=db.doc(`rooms/${code}/players/${uid}`);await db.runTransaction(async(tx)=>{const existing=await tx.get(guessRef);if(existing.exists)throw new HttpsError("already-exists","Guess already submitted.");tx.set(guessRef,{uid,round,guess:{lat,lng},distanceKm,score,submittedAt:FieldValue.serverTimestamp()});tx.update(playerRef,{totalScore:FieldValue.increment(score),lastRoundScore:score,hasGuessedCurrentRound:true});});return {distanceKm,score,guess:{lat,lng}}; });

export const revealRound=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);await assertMember(code,uid);const {room,game}=await roomAndPrivate(code);if(room.phase!=="guessing")return {ok:true};const guesses=await db.collection(`rooms/${code}/rounds/${room.currentRound}/guesses`).get();const players=await db.collection(`rooms/${code}/players`).get();const expired=room.roundEndsAt.toMillis()<=Date.now();if(uid!==room.hostUid&&!expired&&guesses.size<players.size)throw new HttpsError("permission-denied","The host can reveal early, or wait for all guesses.");const results={};guesses.forEach((snap)=>{results[snap.id]=snap.data();});const location=game.locations[room.currentRound-1];await db.doc(`rooms/${code}`).update({phase:"results",revealedLocation:location,roundResults:results,updatedAt:FieldValue.serverTimestamp()});return {ok:true}; });

export const nextRound=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);await assertMember(code,uid);const {room,game}=await roomAndPrivate(code);if(room.hostUid!==uid)throw new HttpsError("permission-denied","Only the host can continue.");if(room.phase!=="results")throw new HttpsError("failed-precondition","Reveal the round first.");if(room.currentRound>=room.roundCount){await finishMatch(code,room);return {finished:true};}await prepareRound(code,room,game,room.currentRound+1);return {finished:false}; });

async function finishMatch(code,room){ const players=await db.collection(`rooms/${code}/players`).get();const sorted=players.docs.map((d)=>({uid:d.id,...d.data()})).sort((a,b)=>(b.totalScore||0)-(a.totalScore||0));const winner=sorted[0]?.uid;const profiles=await Promise.all(sorted.map((player)=>db.doc(`users/${player.uid}`).get()));const batch=db.batch();batch.update(db.doc(`rooms/${code}`),{status:"finished",phase:"finished",finishedAt:FieldValue.serverTimestamp(),winnerUid:winner||null});for(const [index,player] of sorted.entries()){const userRef=db.doc(`users/${player.uid}`);const ratingDelta=player.uid===winner?25:Math.max(-12,Math.round(8-index*5));const previousBest=profiles[index].data()?.bestScore||0;batch.set(userRef,{games:FieldValue.increment(1),wins:FieldValue.increment(player.uid===winner?1:0),rating:FieldValue.increment(ratingDelta),bestScore:Math.max(previousBest,player.totalScore||0),lastMatchAt:FieldValue.serverTimestamp()},{merge:true});}await batch.commit(); }

export const rematch=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);const {room}=await roomAndPrivate(code);if(room.hostUid!==uid)throw new HttpsError("permission-denied","Only the host can rematch.");const players=await db.collection(`rooms/${code}/players`).get();const batch=db.batch();players.forEach((snap)=>batch.update(snap.ref,{ready:snap.id===uid,totalScore:0,lastRoundScore:0,hasGuessedCurrentRound:false}));batch.update(db.doc(`rooms/${code}`),{status:"lobby",phase:"lobby",currentRound:0,currentPanoId:FieldValue.delete(),roundResults:{},revealedLocation:FieldValue.delete(),updatedAt:FieldValue.serverTimestamp()});await batch.commit();return {ok:true}; });

export const leaveRoom=onCall(options,async(request)=>{ const uid=requireAuth(request);const code=cleanCode(request.data?.roomCode);const roomRef=db.doc(`rooms/${code}`);const roomSnap=await roomRef.get();if(!roomSnap.exists)return {ok:true};const room=roomSnap.data();await db.doc(`rooms/${code}/players/${uid}`).delete();if(room.hostUid===uid&&room.status==="lobby"){const players=await db.collection(`rooms/${code}/players`).orderBy("joinedAt").limit(1).get();if(players.empty){await Promise.all([roomRef.delete(),db.doc(`rooms/${code}/private/game`).delete()]);}else await roomRef.update({hostUid:players.docs[0].id});}return {ok:true}; });

export const sendFriendRequest=onCall(options,async(request)=>{ const uid=requireAuth(request);const targetUid=String(request.data?.targetUid||"").trim();if(!targetUid||targetUid===uid)throw new HttpsError("invalid-argument","Enter another player's ID.");const [sender,target]=await Promise.all([userProfile(uid),userProfile(targetUid)]);await db.doc(`users/${targetUid}/friendRequests/${uid}`).set({displayName:sender.displayName||"Explorer",photoURL:sender.photoURL||"",createdAt:FieldValue.serverTimestamp()});return {target:target.displayName}; });

export const acceptFriendRequest=onCall(options,async(request)=>{ const uid=requireAuth(request);const requesterUid=String(request.data?.requesterUid||"").trim();const requestRef=db.doc(`users/${uid}/friendRequests/${requesterUid}`);const requestSnap=await requestRef.get();if(!requestSnap.exists)throw new HttpsError("not-found","Friend request not found.");const [me,friend]=await Promise.all([userProfile(uid),userProfile(requesterUid)]);const batch=db.batch();batch.set(db.doc(`users/${uid}/friends/${requesterUid}`),{displayName:friend.displayName||"Explorer",photoURL:friend.photoURL||"",online:false,createdAt:FieldValue.serverTimestamp()});batch.set(db.doc(`users/${requesterUid}/friends/${uid}`),{displayName:me.displayName||"Explorer",photoURL:me.photoURL||"",online:false,createdAt:FieldValue.serverTimestamp()});batch.delete(requestRef);await batch.commit();return {ok:true}; });
