import { initializeApp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { getFirestore, doc, collection, onSnapshot, getDoc, setDoc, query, orderBy, limit, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { getFunctions, httpsCallable } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
import { runtimeConfig } from "./runtime-config.js";

const $ = (id) => document.getElementById(id);
const screens = [...document.querySelectorAll(".screen")];
const state = { user:null, profile:null, roomCode:null, room:null, players:[], roomUnsubs:[], socialUnsubs:[], guess:null, guessMap:null, guessMarker:null, panorama:null, resultMap:null, resultMarkers:[], timer:null, lastResult:null, firebaseReady:false, mapsReady:false };
const requiredConfig = {
  "Firebase API key": runtimeConfig.firebase.apiKey,
  "Firebase auth domain": runtimeConfig.firebase.authDomain,
  "Firebase project ID": runtimeConfig.firebase.projectId,
  "Firebase app ID": runtimeConfig.firebase.appId,
  "Google Maps browser key": runtimeConfig.googleMapsBrowserKey
};
const missingConfig = Object.entries(requiredConfig).filter(([,v]) => !v || String(v).includes("REPLACE"));
let auth, db, functions;

function showScreen(id){ screens.forEach((screen)=>screen.classList.toggle("is-active",screen.id===id)); }
function toast(message){ const el=$("toast"); el.textContent=message; el.classList.add("is-visible"); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove("is-visible"),2600); }
function showError(error){ console.error(error); toast(error?.message?.replace("FirebaseError: ","") || "Something went wrong."); }
function escapeHtml(value=""){ return String(value).replace(/[&<>'"]/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
function formatScore(value=0){ return Math.round(value).toLocaleString(); }
function rankName(rating=1000){ if(rating>=1700)return"EXPLORER ELITE";if(rating>=1400)return"PATHFINDER";if(rating>=1150)return"NAVIGATOR";return"ROOKIE"; }
function playerAvatar(player){ return player.photoURL || "data:image/svg+xml,"+encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='80' height='80'><rect width='80' height='80' fill='#1a2330'/><text x='40' y='48' font-family='Arial' font-size='28' text-anchor='middle' fill='#c9ff45'>${(player.displayName||"G")[0]}</text></svg>`); }
function updateConnection(online,text="ONLINE"){ const pill=$("connection-pill"); pill.textContent=text; pill.classList.toggle("is-online",online); }
function callable(name){ return httpsCallable(functions,name); }
async function call(name,data={}){ if(!state.firebaseReady)throw new Error("Firebase is not configured."); const result=await callable(name)(data); return result.data; }

async function loadGoogleMaps(){ if(state.mapsReady)return; if(!runtimeConfig.googleMapsBrowserKey)throw new Error("Google Maps API key is missing."); await new Promise((resolve,reject)=>{ const existing=document.querySelector("script[data-geoscope-maps]"); if(existing){ existing.addEventListener("load",resolve,{once:true}); existing.addEventListener("error",reject,{once:true}); return; } const script=document.createElement("script"); script.dataset.geoscopeMaps="1"; script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(runtimeConfig.googleMapsBrowserKey)}&v=weekly&libraries=geometry`; script.async=true; script.onload=resolve; script.onerror=()=>reject(new Error("Google Maps failed to load.")); document.head.appendChild(script); }); state.mapsReady=true; }

function updateProfileUI(){ const p=state.profile||{}; $("rating-value").textContent=formatScore(p.rating||1000); $("rating-rank").textContent=rankName(p.rating||1000); $("games-value").textContent=p.games||0; $("wins-value").textContent=p.wins||0; $("best-score-value").textContent=formatScore(p.bestScore||0); $("profile-name").textContent=p.displayName||state.user?.displayName||"Player"; $("profile-rating").textContent=formatScore(p.rating||1000); $("profile-games").textContent=p.games||0; $("profile-wins").textContent=p.wins||0; $("profile-best").textContent=formatScore(p.bestScore||0); $("player-id").textContent=state.user?.uid||"—"; const avatar=$("profile-button"); if(p.photoURL||state.user?.photoURL){ $("avatar-image").src=p.photoURL||state.user.photoURL; avatar.classList.add("has-image"); } else { avatar.classList.remove("has-image"); $("avatar-fallback").textContent=(p.displayName||state.user?.displayName||"G")[0]; } }

async function ensureProfile(user){ const ref=doc(db,"users",user.uid); const snapshot=await getDoc(ref); if(!snapshot.exists()){ await setDoc(ref,{displayName:user.displayName||"Explorer",email:user.email||"",photoURL:user.photoURL||"",rating:1000,games:0,wins:0,bestScore:0,createdAt:serverTimestamp(),lastSeenAt:serverTimestamp()}); } else { await setDoc(ref,{displayName:user.displayName||snapshot.data().displayName,email:user.email||snapshot.data().email,photoURL:user.photoURL||snapshot.data().photoURL,lastSeenAt:serverTimestamp()},{merge:true}); } onSnapshot(ref,(snap)=>{ state.profile=snap.data(); updateProfileUI(); }); }

function cleanupRoomListeners(){ state.roomUnsubs.forEach((unsub)=>unsub()); state.roomUnsubs=[]; clearInterval(state.timer); state.timer=null; }
function subscribeRoom(code){ cleanupRoomListeners(); state.roomCode=code; const roomRef=doc(db,"rooms",code); state.roomUnsubs.push(onSnapshot(roomRef,(snap)=>{ if(!snap.exists()){ toast("Room no longer exists."); leaveRoomLocal(); return; } state.room={id:snap.id,...snap.data()}; renderRoom(); })); const playersQuery=query(collection(db,"rooms",code,"players"),orderBy("joinedAt","asc")); state.roomUnsubs.push(onSnapshot(playersQuery,(snapshot)=>{ state.players=snapshot.docs.map((d)=>({uid:d.id,...d.data()})); renderPlayers(); renderScoreboards(); })); }
function leaveRoomLocal(){ cleanupRoomListeners(); state.room=null;state.roomCode=null;state.players=[];showScreen("dashboard-screen"); }

function renderRoom(){ const room=state.room;if(!room)return; if(room.status==="lobby"){ showScreen("lobby-screen"); $("lobby-code").textContent=room.id; $("lobby-status").textContent=room.hostUid===state.user.uid?"You are the host. Start when everyone is ready.":"Waiting for the host to start."; $("round-count").value=String(room.roundCount||5); $("round-time").value=String(room.roundSeconds||90); const host=room.hostUid===state.user.uid; $("round-count").disabled=!host; $("round-time").disabled=!host; $("start-room").classList.toggle("is-hidden",!host); updateStartButton(); return; }
  if(room.status==="playing"){ if(room.phase==="guessing"){ showScreen("game-screen"); beginRoundView(); } else if(room.phase==="results"){ showRoundResults(); } return; }
  if(room.status==="finished")showFinal();
}
function renderPlayers(){ $("player-count").textContent=`${state.players.length} / 8`; $("players-list").innerHTML=state.players.map((p)=>`<div class="player-row"><img class="player-avatar" src="${escapeHtml(playerAvatar(p))}" alt=""/><div class="player-meta"><strong>${escapeHtml(p.displayName||"Explorer")}${p.uid===state.room?.hostUid?" · HOST":""}</strong><span>${formatScore(p.totalScore||0)} points</span></div><span class="ready-badge ${p.ready?"is-ready":""}">${p.ready?"READY":"WAITING"}</span></div>`).join(""); const me=state.players.find((p)=>p.uid===state.user?.uid); $("ready-button").textContent=me?.ready?"NOT READY":"I'M READY"; updateStartButton(); }
function updateStartButton(){ if(!state.room||state.room.hostUid!==state.user?.uid)return; const enough=state.players.length>=1; const ready=state.players.every((p)=>p.ready||p.uid===state.room.hostUid); $("start-room").disabled=!(enough&&ready); }
function renderScoreboards(){ const sorted=[...state.players].sort((a,b)=>(b.totalScore||0)-(a.totalScore||0)); $("live-score-list").innerHTML=sorted.map((p,i)=>`<div class="score-row"><span class="score-rank">${i+1}</span><img src="${escapeHtml(playerAvatar(p))}" alt=""/><div><strong>${escapeHtml(p.displayName||"Explorer")}</strong><span>${p.hasGuessedCurrentRound?"GUESS LOCKED":"PLAYING"}</span></div><strong class="score-points">${formatScore(p.totalScore||0)}</strong></div>`).join(""); }

async function beginRoundView(){ const room=state.room;if(!room?.currentPanoId)return; await loadGoogleMaps(); $("game-round").textContent=`ROUND ${room.currentRound} / ${room.roundCount}`; $("round-progress").style.width=`${(room.currentRound/room.roundCount)*100}%`; state.guess=null; $("submit-guess").disabled=true; $("guess-coordinate").textContent="Select a location on the map"; $("guess-drawer").classList.remove("is-open"); $("guess-drawer").setAttribute("aria-hidden","true"); if(!state.panorama){ state.panorama=new google.maps.StreetViewPanorama($("street-view"),{pano:room.currentPanoId,addressControl:false,showRoadLabels:false,linksControl:true,panControl:true,zoomControl:true,fullscreenControl:false,enableCloseButton:false,clickToGo:true}); } else { state.panorama.setPano(room.currentPanoId); state.panorama.setPov({heading:0,pitch:0}); state.panorama.setZoom(1); }
  if(!state.guessMap){ state.guessMap=new google.maps.Map($("guess-map"),{center:{lat:18,lng:5},zoom:2,minZoom:2,streetViewControl:false,mapTypeControl:false,fullscreenControl:false,gestureHandling:"greedy",styles:[{elementType:"geometry",stylers:[{color:"#18212a"}]},{elementType:"labels.text.fill",stylers:[{color:"#98a7b7"}]},{elementType:"labels.text.stroke",stylers:[{color:"#10161d"}]},{featureType:"water",elementType:"geometry",stylers:[{color:"#0d1721"}]}]}); state.guessMap.addListener("click",({latLng})=>{ state.guess={lat:latLng.lat(),lng:latLng.lng()}; if(!state.guessMarker)state.guessMarker=new google.maps.Marker({map:state.guessMap,position:state.guess}); else state.guessMarker.setPosition(state.guess); $("guess-coordinate").textContent=`${state.guess.lat.toFixed(3)}, ${state.guess.lng.toFixed(3)}`; $("submit-guess").disabled=false; }); }
  startTimer(room.roundEndsAt);
}
function startTimer(timestamp){ clearInterval(state.timer); const tick=()=>{ const end=timestamp?.toMillis?timestamp.toMillis():new Date(timestamp).getTime(); const left=Math.max(0,Math.ceil((end-Date.now())/1000)); $("game-timer").textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`; if(left<=0){ clearInterval(state.timer); if(state.room?.hostUid===state.user?.uid)call("revealRound",{roomCode:state.roomCode}).catch(()=>{}); } };tick();state.timer=setInterval(tick,500); }

async function submitGuess(){ if(!state.guess)return; $("submit-guess").disabled=true; const result=await call("submitGuess",{roomCode:state.roomCode,round:state.room.currentRound,lat:state.guess.lat,lng:state.guess.lng}); state.lastResult=result; $("guess-drawer").classList.remove("is-open"); toast(`Guess locked · ${formatScore(result.score)} points`); }
async function showRoundResults(){ clearInterval(state.timer); await loadGoogleMaps(); showScreen("result-screen"); const room=state.room; const myGuess=room.roundResults?.[state.user.uid]||state.lastResult; $("result-distance").textContent=myGuess?`${Math.round(myGuess.distanceKm).toLocaleString()} km`:"NO GUESS"; $("result-score").textContent=myGuess?formatScore(myGuess.score):"0"; $("result-location").textContent=room.revealedLocation?`${room.revealedLocation.city}, ${room.revealedLocation.country}`:"Waiting for reveal"; const host=room.hostUid===state.user.uid; $("reveal-round").classList.toggle("is-hidden",room.phase==="results"||!host); $("next-round").classList.toggle("is-hidden",!host); $("next-round").textContent=room.currentRound>=room.roundCount?"FINAL RESULTS →":"NEXT ROUND →"; renderRoundScoreboard(room.roundResults||{}); renderResultMap(room.revealedLocation,myGuess); }
function renderRoundScoreboard(results){ const rows=state.players.map((p)=>({p,r:results[p.uid]})).sort((a,b)=>(b.r?.score||0)-(a.r?.score||0)); $("round-scoreboard").innerHTML=rows.map(({p,r},i)=>`<div class="score-row"><span class="score-rank">${i+1}</span><img src="${escapeHtml(playerAvatar(p))}" alt=""/><div><strong>${escapeHtml(p.displayName||"Explorer")}</strong><span>${r?`${Math.round(r.distanceKm).toLocaleString()} KM`:"NO GUESS"}</span></div><strong class="score-points">${formatScore(r?.score||0)}</strong></div>`).join(""); }
function renderResultMap(actual,myGuess){ if(!actual)return; if(!state.resultMap)state.resultMap=new google.maps.Map($("result-map"),{center:{lat:actual.lat,lng:actual.lng},zoom:4,streetViewControl:false,mapTypeControl:false,fullscreenControl:false}); state.resultMarkers.forEach((m)=>m.setMap?.(null));state.resultMarkers=[]; const actualPos={lat:actual.lat,lng:actual.lng}; state.resultMarkers.push(new google.maps.Marker({map:state.resultMap,position:actualPos,label:"A"})); if(myGuess?.guess){ const guessPos=myGuess.guess; state.resultMarkers.push(new google.maps.Marker({map:state.resultMap,position:guessPos,label:"G"})); state.resultMarkers.push(new google.maps.Polyline({map:state.resultMap,path:[actualPos,guessPos],geodesic:true,strokeColor:"#c9ff45",strokeOpacity:.9,strokeWeight:3})); const bounds=new google.maps.LatLngBounds();bounds.extend(actualPos);bounds.extend(guessPos);state.resultMap.fitBounds(bounds,70); } else state.resultMap.setCenter(actualPos); }
function showFinal(){ showScreen("final-screen"); const sorted=[...state.players].sort((a,b)=>(b.totalScore||0)-(a.totalScore||0)); $("final-standings").innerHTML=sorted.map((p,i)=>`<div class="standing-row"><strong>${i+1}</strong><img src="${escapeHtml(playerAvatar(p))}" alt=""/><div><strong>${escapeHtml(p.displayName||"Explorer")}</strong><span>${p.uid===state.room?.hostUid?"HOST":"PLAYER"}</span></div><strong>${formatScore(p.totalScore||0)}</strong></div>`).join(""); $("rematch-button").classList.toggle("is-hidden",state.room?.hostUid!==state.user?.uid); }

async function loadFriends(){ if(!state.user)return; state.socialUnsubs.forEach((unsub)=>unsub()); state.socialUnsubs=[]; const requestsQuery=query(collection(db,"users",state.user.uid,"friendRequests"),orderBy("createdAt","desc"),limit(20)); state.socialUnsubs.push(onSnapshot(requestsQuery,(snap)=>{ $("friend-requests").innerHTML=snap.empty?`<p class="auth-note">No pending requests.</p>`:snap.docs.map((d)=>{const r=d.data();return `<div class="friend-row"><img src="${escapeHtml(playerAvatar(r))}" alt=""/><div><strong>${escapeHtml(r.displayName||"Explorer")}</strong><span>${escapeHtml(d.id)}</span></div><button class="secondary-button accept-friend" data-uid="${escapeHtml(d.id)}" type="button">ACCEPT</button></div>`}).join(""); })); const friendsQuery=query(collection(db,"users",state.user.uid,"friends"),orderBy("displayName","asc"),limit(100)); state.socialUnsubs.push(onSnapshot(friendsQuery,(snap)=>{ $("friends-list").innerHTML=snap.empty?`<p class="auth-note">Add friends using their player ID.</p>`:snap.docs.map((d)=>{const f=d.data();return `<div class="friend-row"><img src="${escapeHtml(playerAvatar(f))}" alt=""/><div><strong>${escapeHtml(f.displayName||"Explorer")}</strong><span>${f.online?"ONLINE":"OFFLINE"}</span></div></div>`}).join(""); })); }

function openSetup(){ $("missing-config-list").innerHTML=missingConfig.map(([name])=>`<div class="missing-item">${escapeHtml(name)} is not configured</div>`).join(""); $("setup-dialog").showModal(); }
async function init(){ if(missingConfig.length){ updateConnection(false,"SETUP REQUIRED"); openSetup(); return; } const app=initializeApp(runtimeConfig.firebase); auth=getAuth(app);db=getFirestore(app);functions=getFunctions(app,runtimeConfig.functionsRegion||"europe-west1");state.firebaseReady=true;updateConnection(true);onAuthStateChanged(auth,async(user)=>{ state.user=user; $("friends-button").classList.toggle("is-hidden",!user);$("profile-button").classList.toggle("is-hidden",!user);if(!user){cleanupRoomListeners();state.socialUnsubs.forEach((unsub)=>unsub());state.socialUnsubs=[];showScreen("auth-screen");return;}try{await ensureProfile(user);showScreen("dashboard-screen");loadFriends();const code=new URLSearchParams(location.search).get("room");if(code){$("room-code-input").value=code.toUpperCase();await joinRoom();}}catch(error){showError(error);}}); }

async function createRoom(solo=false){ const data=await call("createRoom",{roundCount:Number($("round-count")?.value||5),roundSeconds:Number($("round-time")?.value||90),solo});subscribeRoom(data.roomCode);history.replaceState(null,"",`?room=${data.roomCode}`); }
async function joinRoom(){ const code=$("room-code-input").value.trim().toUpperCase();if(!code)return toast("Enter a room code.");await call("joinRoom",{roomCode:code});subscribeRoom(code);history.replaceState(null,"",`?room=${code}`); }

$("google-sign-in").addEventListener("click",()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(showError));
$("sign-out").addEventListener("click",()=>signOut(auth).catch(showError));
$("create-room").addEventListener("click",()=>createRoom(false).catch(showError));
$("solo-game").addEventListener("click",()=>createRoom(true).catch(showError));
$("join-room").addEventListener("click",()=>joinRoom().catch(showError));
$("room-code-input").addEventListener("keydown",(event)=>{if(event.key==="Enter")joinRoom().catch(showError);});
$("ready-button").addEventListener("click",()=>call("toggleReady",{roomCode:state.roomCode}).catch(showError));
$("start-room").addEventListener("click",()=>call("startGame",{roomCode:state.roomCode,roundCount:Number($("round-count").value),roundSeconds:Number($("round-time").value)}).catch(showError));
$("leave-room").addEventListener("click",async()=>{try{await call("leaveRoom",{roomCode:state.roomCode});}catch{}history.replaceState(null,"",location.pathname);leaveRoomLocal();});
$("copy-invite").addEventListener("click",async()=>{await navigator.clipboard.writeText(`${location.origin}${location.pathname}?room=${state.roomCode}`);toast("Invite link copied.");});
$("open-guess-map").addEventListener("click",()=>{$("guess-drawer").classList.add("is-open");$("guess-drawer").setAttribute("aria-hidden","false");setTimeout(()=>google.maps.event.trigger(state.guessMap,"resize"),100);});
$("close-guess-map").addEventListener("click",()=>{$("guess-drawer").classList.remove("is-open");$("guess-drawer").setAttribute("aria-hidden","true");});
$("submit-guess").addEventListener("click",()=>submitGuess().catch(showError));
$("leaderboard-toggle").addEventListener("click",()=>$("live-leaderboard").classList.toggle("is-open"));
$("reveal-round").addEventListener("click",()=>call("revealRound",{roomCode:state.roomCode}).catch(showError));
$("next-round").addEventListener("click",()=>call("nextRound",{roomCode:state.roomCode}).catch(showError));
$("back-dashboard").addEventListener("click",()=>{history.replaceState(null,"",location.pathname);leaveRoomLocal();});
$("rematch-button").addEventListener("click",()=>call("rematch",{roomCode:state.roomCode}).catch(showError));
$("profile-button").addEventListener("click",()=>$("profile-dialog").showModal());
$("friends-button").addEventListener("click",()=>$("friends-dialog").showModal());
$("copy-player-id").addEventListener("click",async()=>{await navigator.clipboard.writeText(state.user.uid);toast("Player ID copied.");});
$("add-friend").addEventListener("click",()=>call("sendFriendRequest",{targetUid:$("friend-id-input").value.trim()}).then(()=>{toast("Friend request sent.");$("friend-id-input").value="";}).catch(showError));
$("friend-requests").addEventListener("click",(event)=>{const button=event.target.closest(".accept-friend");if(button)call("acceptFriendRequest",{requesterUid:button.dataset.uid}).then(()=>toast("Friend added.")).catch(showError);});
document.querySelectorAll("[data-close-dialog]").forEach((button)=>button.addEventListener("click",()=>$(button.dataset.closeDialog).close()));
document.querySelectorAll("[data-action='home']").forEach((button)=>button.addEventListener("click",()=>{if(state.user)showScreen("dashboard-screen");else showScreen("auth-screen");}));

init().catch(showError);
