(() => {
'use strict';
const $ = id => document.getElementById(id);
const I18N = window.GeoScopeI18n;
const MAP_STYLE='https://tiles.openfreemap.org/styles/liberty';
const LOCATIONS=[
 ['London','United Kingdom','gb',51.50084,-.1225,270,1,'capital',1],['Paris','France','fr',48.85888,2.29893,275,1,'capital',1],['Rome','Italy','it',41.89084,12.49167,205,1,'capital',1],['Berlin','Germany','de',52.51648,13.3791,265,1,'capital',1],['Madrid','Spain','es',40.41694,-3.70345,130,1,'capital',1],['Helsinki','Finland','fi',60.16962,24.95172,120,1,'capital',1],['Washington','United States','us',38.8974,-77.03648,190,1,'capital',1],['Tokyo','Japan','jp',35.65944,139.7005,25,1,'capital',1],['Seoul','South Korea','kr',37.57212,126.97675,5,2,'capital',0],['Lisbon','Portugal','pt',38.72091,-9.14595,350,2,'capital',0],['Vienna','Austria','at',48.20452,16.3611,85,2,'capital',0],['Copenhagen','Denmark','dk',55.68001,12.58804,250,2,'capital',0],['Stockholm','Sweden','se',59.33242,18.06489,55,2,'capital',0],['Oslo','Norway','no',59.91351,10.7392,80,2,'capital',0],['Prague','Czechia','cz',50.08102,14.42566,320,2,'capital',0],['Budapest','Hungary','hu',47.50244,19.05954,55,2,'capital',0],['Tallinn','Estonia','ee',59.43858,24.75769,270,3,'capital',0],['Montevideo','Uruguay','uy',-34.90627,-56.19172,80,3,'capital',0],['Wellington','New Zealand','nz',-41.2827,174.77642,20,3,'capital',0],
 ['New York','United States','us',40.75818,-73.9851,55,1,'major',1],['Barcelona','Spain','es',41.40346,2.17397,40,1,'major',1],['Amsterdam','Netherlands','nl',52.37432,4.89518,185,1,'major',1],['Sydney','Australia','au',-33.86114,151.21056,35,1,'major',1],['San Francisco','United States','us',37.80766,-122.47524,295,1,'major',1],['Dubai','United Arab Emirates','ae',25.197,55.2743,20,1,'major',1],['Singapore','Singapore','sg',1.2839,103.8609,45,1,'major',1],['Toronto','Canada','ca',43.65509,-79.38025,5,2,'major',0],['Mexico City','Mexico','mx',19.42724,-99.16765,65,2,'major',0],['Buenos Aires','Argentina','ar',-34.60366,-58.38171,10,2,'major',0],['Cape Town','South Africa','za',-33.92432,18.41578,15,2,'major',0],['Auckland','New Zealand','nz',-36.85092,174.76452,5,2,'major',0],['Busan','South Korea','kr',35.15768,129.0593,210,3,'city',0],['Porto','Portugal','pt',41.1448,-8.61035,185,3,'city',0],['Adelaide','Australia','au',-34.92281,138.60477,95,3,'city',0],['Curitiba','Brazil','br',-25.42965,-49.27133,85,3,'city',0],['Kaohsiung','Taiwan','tw',22.61395,120.30498,25,3,'city',0],['Sapporo','Japan','jp',43.06064,141.35439,90,3,'city',0],['Malmö','Sweden','se',55.60549,13.00355,175,3,'city',0],['Zaragoza','Spain','es',41.64984,-.88233,350,3,'city',0],['Thessaloniki','Greece','gr',40.6369,22.94412,90,3,'city',0],['Ghent','Belgium','be',51.05439,3.72197,190,3,'city',0],
 ['Great Ocean Road','Australia','au',-38.66404,143.10446,250,2,'scenic',0],['Iceland Ring Road','Iceland','is',63.61664,-19.98891,95,2,'scenic',0],['Tuscany','Italy','it',43.31808,11.33082,120,2,'scenic',0],['Lofoten','Norway','no',68.20824,13.50518,75,2,'scenic',0],['Lake Tekapo','New Zealand','nz',-44.00474,170.47768,40,2,'scenic',0],['Canadian Rockies','Canada','ca',51.1777,-115.5716,300,2,'scenic',0],['Patagonia','Argentina','ar',-50.33766,-72.2649,20,3,'remote',0],['Namib Road','Namibia','na',-24.74844,15.30044,140,3,'remote',0],['Faroe Islands','Faroe Islands','fo',62.01945,-6.77128,10,3,'scenic',0],['Atacama approach','Chile','cl',-22.9065,-68.1987,45,3,'remote',0]
].map(x=>({city:x[0],country:x[1],cc:x[2],lat:x[3],lng:x[4],heading:x[5],difficulty:x[6],kind:x[7],famous:x[8]}));
const FORMATS={classic:{rounds:5,seconds:90},sprint:{rounds:5,seconds:35},duel:{rounds:20,seconds:60,duel:true},endurance:{rounds:10,seconds:120}};
const params=new URLSearchParams(location.search);
let cfg=Object.assign({format:'classic',pool:'smart',difficulty:1,lang:'en'},readJson('geoCfg',{}));
for(const key of ['format','pool','lang'])if(params.has(key))cfg[key]=params.get(key);if(params.has('difficulty'))cfg.difficulty=Number(params.get('difficulty'))||1;
if(!I18N.languageNames[cfg.lang])cfg.lang='en';writeJson('geoCfg',cfg);
let profile=Object.assign({matches:0,wins:0,totalScore:0,best:0,rounds:0,countryHits:0,totalKm:0,totalTime:0,history:[],choices:{},coins:248},readJson('geoProProfile',{}));
let match=[],roundIndex=0,guess=null,guessMap=null,resultMap=null,guessMarker=null,timerId=null,seconds=0,totalSeconds=0,totalScore=0,youHp=6000,aiHp=6000,lastResult=null,finishing=false;
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(_){}}
function t(key,vars){return I18N.t(cfg.lang,key,vars)}
function applyLanguage(){document.documentElement.lang=cfg.lang;document.documentElement.dir=cfg.lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n))}
function show(id){document.querySelectorAll('.screen').forEach(el=>el.classList.toggle('active',el.id===id))}
function key(){return String(window.GEOSCOPE_CONFIG?.googleMapsApiKey||'').trim()}
function home(){clearInterval(timerId);$('streetView').src='about:blank';location.href='geoscope.html#app'}
function fail(error){console.error(error);clearInterval(timerId);$('runtimeErrorText').textContent=error?.message||String(error||t('arena.errorGeneric'));$('runtimeError').hidden=false}
function poolWeight(x){if(cfg.pool==='cities')return['capital','major','city'].includes(x.kind)?1:0;if(cfg.pool==='capitals')return x.kind==='capital'?1:0;if(cfg.pool==='famous')return x.famous?1:0;if(cfg.pool==='megacities')return x.kind==='major'?1:0;if(cfg.pool==='scenic')return['scenic','remote'].includes(x.kind)?1:0;return{capital:3.4,major:5,city:4,scenic:1.4,remote:.35}[x.kind]||1}
function difficultyWeight(x){const delta=Math.abs(x.difficulty-Number(cfg.difficulty));return delta===0?7:delta===1?1.8:.25}
function weightedSample(count){const remaining=[...LOCATIONS],picked=[];while(picked.length<count&&remaining.length){const weights=remaining.map(x=>poolWeight(x)*difficultyWeight(x)),total=weights.reduce((a,b)=>a+b,0);if(total<=0)break;let roll=Math.random()*total,index=0;for(;index<weights.length;index++){roll-=weights[index];if(roll<=0)break}picked.push(remaining.splice(Math.min(index,remaining.length-1),1)[0])}return picked}
function streetUrl(loc){return'https://www.google.com/maps/embed/v1/streetview?'+new URLSearchParams({key:key(),location:`${loc.lat},${loc.lng}`,heading:String(loc.heading||0),pitch:'0',fov:'90',radius:'120',source:'outdoor'})}
function startMatch(){try{if(!key())throw new Error(t('arena.noKey'));const format=FORMATS[cfg.format]||FORMATS.classic;match=weightedSample(format.rounds);if(match.length<format.rounds)throw new Error(t('arena.notEnough'));roundIndex=0;guess=null;totalScore=0;youHp=aiHp=6000;finishing=false;profile.choices[cfg.format]=(profile.choices[cfg.format]||0)+1;profile.choices[cfg.pool]=(profile.choices[cfg.pool]||0)+1;show('game');startRound()}catch(error){fail(error)}}
function startRound(){clearInterval(timerId);guess=null;const format=FORMATS[cfg.format],loc=match[roundIndex];$('guessPanel').classList.remove('open');$('submitGuess').disabled=true;$('coords').textContent=t('arena.click');if(guessMarker){guessMarker.remove();guessMarker=null}if(guessMap)guessMap.jumpTo({center:[0,20],zoom:1.7});$('gameMode').textContent=`${t(`format.${cfg.format}.name`).toUpperCase()} · ${t(`pool.${cfg.pool}.name`).toUpperCase()}`;$('roundLabel').textContent=`${t('common.round').toUpperCase()} ${roundIndex+1}${format.duel?'':' / '+match.length}`;$('roundProgress').style.width=`${Math.min(100,(roundIndex+1)/match.length*100)}%`;$('streetView').src=streetUrl(loc);$('duelHud').hidden=!format.duel;updateHp();totalSeconds=seconds=format.seconds;tick();showIntro();timerId=setInterval(()=>{seconds--;tick();if(seconds<=0){clearInterval(timerId);guess={lat:0,lng:0};finishRound(true)}},1000)}
function tick(){$('timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('timer').style.color=seconds<=10?'var(--red)':'var(--lime)'}
function showIntro(){$('introMode').textContent=t(`pool.${cfg.pool}.name`).toUpperCase();$('introRound').textContent=`${t('common.round').toUpperCase()} ${roundIndex+1}`;$('introDifficulty').textContent=t(`difficulty.${cfg.difficulty}.name`).toUpperCase();const el=$('roundIntro');el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function ensureGuessMap(){if(guessMap)return;if(!window.maplibregl)throw new Error(t('arena.mapError'));guessMap=new maplibregl.Map({container:'guessMap',style:MAP_STYLE,center:[0,20],zoom:1.7,attributionControl:true});guessMap.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');guessMap.on('click',event=>{guess={lat:event.lngLat.lat,lng:event.lngLat.lng};if(guessMarker)guessMarker.remove();const el=document.createElement('div');el.style.cssText='width:24px;height:24px;border-radius:50% 50% 50% 0;background:#caff46;border:4px solid #111;transform:rotate(-45deg);box-shadow:0 0 20px rgba(202,255,70,.45)';guessMarker=new maplibregl.Marker({element:el}).setLngLat([guess.lng,guess.lat]).addTo(guessMap);$('coords').textContent=`${Math.abs(guess.lat).toFixed(2)}° ${guess.lat>=0?'N':'S'}, ${Math.abs(guess.lng).toFixed(2)}° ${guess.lng>=0?'E':'W'}`;$('submitGuess').disabled=false})}
function distanceKm(a,b,c,d){const rad=x=>x*Math.PI/180,R=6371,dy=rad(c-a),dx=rad(d-b),h=Math.sin(dy/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dx/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
async function reverseCountry(point){const cacheKey=`${point.lat.toFixed(2)},${point.lng.toFixed(2)}`;try{const cache=readJson('geoCountryCache',{});if(cache[cacheKey])return cache[cacheKey];const url=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=3&addressdetails=1&lat=${point.lat}&lon=${point.lng}`;const response=await fetch(url,{headers:{'Accept-Language':'en'}});if(!response.ok)throw new Error('geocoder');const json=await response.json(),cc=(json.address?.country_code||'').toLowerCase();cache[cacheKey]=cc;writeJson('geoCountryCache',cache);return cc}catch{return''}}
function scoreParts(km,countryHit){const distanceScore=Math.max(0,Math.round(4000*Math.exp(-km/1550))),accuracy=distanceScore/4000,timeRatio=Math.max(0,seconds/totalSeconds),countryScore=countryHit?600:0,speedScore=Math.round(400*Math.pow(timeRatio,.7)*(.25+.75*accuracy));return{distanceScore,countryScore,speedScore,total:Math.min(5000,distanceScore+countryScore+speedScore)}}
function aiScore(){const skill=cfg.difficulty===1?.76:cfg.difficulty===2?.7:.64;return Math.max(200,Math.min(5000,Math.round(2100+skill*2200+(Math.random()-.5)*1500)))}
async function finishRound(timeout){if(!guess||finishing)return;finishing=true;clearInterval(timerId);$('submitGuess').disabled=true;try{const loc=match[roundIndex],km=distanceKm(guess.lat,guess.lng,loc.lat,loc.lng),cc=await reverseCountry(guess),countryHit=cc===loc.cc,parts=scoreParts(km,countryHit),opponent=aiScore();totalScore+=parts.total;profile.rounds++;profile.totalKm+=km;profile.totalTime+=totalSeconds-seconds;if(countryHit)profile.countryHits++;const format=FORMATS[cfg.format];let damage=0,multiplier=1;if(format.duel){multiplier=roundIndex<3?1:roundIndex<6?1.5:roundIndex<9?2:3;damage=Math.round(Math.abs(parts.total-opponent)*multiplier);if(parts.total>=opponent)aiHp=Math.max(0,aiHp-damage);else youHp=Math.max(0,youHp-damage);updateHp()}lastResult={loc,km,countryHit,parts,opponent,damage,multiplier,timeout,timeUsed:totalSeconds-seconds,timeRemaining:seconds};renderResult();show('result');renderResultMap()}catch(error){fail(error)}finally{finishing=false}}
function updateHp(){$('youHp').textContent=youHp.toLocaleString(cfg.lang);$('aiHp').textContent=aiHp.toLocaleString(cfg.lang);$('youHpBar').style.width=(youHp/60)+'%';$('aiHpBar').style.width=(aiHp/60)+'%';$('multiplier').textContent='×'+(roundIndex<3?1:roundIndex<6?1.5:roundIndex<9?2:3)}
function renderResult(){const r=lastResult,format=FORMATS[cfg.format];$('resultRound').textContent=`${t('common.round').toUpperCase()} ${roundIndex+1}`;$('resultTitle').textContent=r.parts.total>4400?t('arena.excellent'):r.countryHit?t('arena.correctCountry'):t('arena.keepReading');$('distanceValue').textContent=r.km<1?`${Math.round(r.km*1000)} m`:`${Math.round(r.km).toLocaleString(cfg.lang)} km`;$('locationName').textContent=`${r.loc.city}, ${r.loc.country}${r.timeout?' · '+t('arena.timeExpired'):''}`;$('distanceScore').textContent=r.parts.distanceScore.toLocaleString(cfg.lang);$('countryScore').textContent=r.parts.countryScore.toLocaleString(cfg.lang);$('speedScore').textContent=r.parts.speedScore.toLocaleString(cfg.lang);$('timeUsed').textContent=`${r.timeUsed}s`;$('timeRemaining').textContent=`${r.timeRemaining}s`;$('roundScore').textContent=r.parts.total.toLocaleString(cfg.lang);$('duelDamage').hidden=!format.duel;$('duelDamage').textContent=format.duel?t(r.parts.total>=r.opponent?'arena.damageYou':'arena.damageAi',{damage:r.damage.toLocaleString(cfg.lang),multiplier:r.multiplier}):'';const finished=(format.duel&&(youHp<=0||aiHp<=0))||(!format.duel&&roundIndex===match.length-1);$('nextRound').textContent=finished?t('arena.finish'):t('arena.next')}
function resultMarker(color){const el=document.createElement('div');el.style.cssText=`width:22px;height:22px;border-radius:50%;background:${color};border:4px solid #111;box-shadow:0 0 18px ${color}66`;return el}
function renderResultMap(){if(resultMap){resultMap.remove();resultMap=null}const r=lastResult;resultMap=new maplibregl.Map({container:'resultMap',style:MAP_STYLE,center:[0,20],zoom:1.4,attributionControl:true});resultMap.on('load',()=>{new maplibregl.Marker({element:resultMarker('#caff46')}).setLngLat([guess.lng,guess.lat]).addTo(resultMap);new maplibregl.Marker({element:resultMarker('#ff7065')}).setLngLat([r.loc.lng,r.loc.lat]).addTo(resultMap);resultMap.addSource('answer-line',{type:'geojson',data:{type:'Feature',geometry:{type:'LineString',coordinates:[[guess.lng,guess.lat],[r.loc.lng,r.loc.lat]]}}});resultMap.addLayer({id:'answer-line',type:'line',source:'answer-line',paint:{'line-color':'#caff46','line-width':3,'line-dasharray':[2,2]}});const bounds=new maplibregl.LngLatBounds().extend([guess.lng,guess.lat]).extend([r.loc.lng,r.loc.lat]);resultMap.fitBounds(bounds,{padding:window.innerWidth<850?{top:65,right:35,bottom:380,left:35}:{top:90,right:520,bottom:70,left:70},maxZoom:7,duration:1200})})}
function nextRound(){const format=FORMATS[cfg.format],finished=(format.duel&&(youHp<=0||aiHp<=0))||(!format.duel&&roundIndex===match.length-1);if(finished){finishMatch();return}roundIndex++;if(format.duel&&roundIndex>=match.length)match.push(...weightedSample(10));show('game');startRound()}
function statCards(items){return items.map(([value,label])=>`<div><b>${value}</b><span>${label}</span></div>`).join('')}
function finishMatch(){const duel=FORMATS[cfg.format].duel,win=duel?aiHp<=0:totalScore>=15000;profile.matches++;if(win)profile.wins++;profile.totalScore+=totalScore;profile.best=Math.max(profile.best,totalScore);profile.coins=Number(profile.coins||248)+Math.max(10,Math.round(totalScore/500));profile.history.unshift({date:new Date().toISOString(),format:cfg.format,pool:cfg.pool,difficulty:cfg.difficulty,score:totalScore,win,rounds:roundIndex+1});profile.history=profile.history.slice(0,30);writeJson('geoProProfile',profile);$('finalTitle').textContent=duel?(win?t('arena.duelWon'):t('arena.duelLost')):t('arena.matchComplete');$('finalScore').textContent=totalScore.toLocaleString(cfg.lang);const rounds=Math.max(1,profile.rounds);$('finalStats').innerHTML=statCards([[roundIndex+1,t('stats.rounds')],[Math.round(profile.totalKm/rounds).toLocaleString(cfg.lang)+' km',t('stats.distance')],[Math.round(profile.countryHits/rounds*100)+'%',t('stats.country')],[Math.round(profile.totalTime/rounds)+'s',t('stats.time')]]);show('final')}
function requestExit(){$('exitDialog').showModal()}
function bind(){
 $('mapTrigger').onclick=()=>{try{ensureGuessMap();$('guessPanel').classList.add('open');setTimeout(()=>guessMap.resize(),260)}catch(error){fail(error)}};$('closeMap').onclick=()=>$('guessPanel').classList.remove('open');$('submitGuess').onclick=()=>finishRound(false);$('nextRound').onclick=nextRound;$('playAgain').onclick=startMatch;$('homeButton').onclick=home;$('exitGame').onclick=requestExit;$('exitResult').onclick=requestExit;$('cancelExit').onclick=()=>$('exitDialog').close();$('confirmExit').onclick=home;$('errorHome').onclick=home;document.addEventListener('keydown',event=>{if(event.key==='Escape'){if($('guessPanel').classList.contains('open'))$('guessPanel').classList.remove('open');else requestExit()}});window.addEventListener('error',event=>fail(event.error||new Error(event.message)));window.addEventListener('unhandledrejection',event=>fail(event.reason))
}
function init(){applyLanguage();bind();setTimeout(startMatch,150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
