(function(){
'use strict';
const MAP_STYLE='https://tiles.openfreemap.org/styles/liberty';
const locations=[
{city:'London',country:'United Kingdom',lat:51.50084,lng:-0.12250,h:270,d:1,k:'capital',famous:1},{city:'Paris',country:'France',lat:48.85888,lng:2.29893,h:275,d:1,k:'capital',famous:1},{city:'Rome',country:'Italy',lat:41.89084,lng:12.49167,h:205,d:1,k:'capital',famous:1},{city:'Berlin',country:'Germany',lat:52.51648,lng:13.37910,h:265,d:1,k:'capital',famous:1},{city:'Madrid',country:'Spain',lat:40.41694,lng:-3.70345,h:130,d:1,k:'capital',famous:1},{city:'Helsinki',country:'Finland',lat:60.16962,lng:24.95172,h:120,d:1,k:'capital',famous:1},{city:'Washington',country:'United States',lat:38.89740,lng:-77.03648,h:190,d:1,k:'capital',famous:1},{city:'Tokyo',country:'Japan',lat:35.65944,lng:139.70050,h:25,d:1,k:'capital',famous:1},{city:'Seoul',country:'South Korea',lat:37.57212,lng:126.97675,h:5,d:2,k:'capital'},{city:'Lisbon',country:'Portugal',lat:38.72091,lng:-9.14595,h:350,d:2,k:'capital'},{city:'Vienna',country:'Austria',lat:48.20452,lng:16.36110,h:85,d:2,k:'capital'},{city:'Copenhagen',country:'Denmark',lat:55.68001,lng:12.58804,h:250,d:2,k:'capital'},{city:'Stockholm',country:'Sweden',lat:59.33242,lng:18.06489,h:55,d:2,k:'capital'},{city:'Oslo',country:'Norway',lat:59.91351,lng:10.73920,h:80,d:2,k:'capital'},{city:'Prague',country:'Czechia',lat:50.08102,lng:14.42566,h:320,d:2,k:'capital'},{city:'Budapest',country:'Hungary',lat:47.50244,lng:19.05954,h:55,d:2,k:'capital'},{city:'Tallinn',country:'Estonia',lat:59.43858,lng:24.75769,h:270,d:3,k:'capital'},{city:'Ljubljana',country:'Slovenia',lat:46.05292,lng:14.50377,h:5,d:3,k:'capital'},{city:'Montevideo',country:'Uruguay',lat:-34.90627,lng:-56.19172,h:80,d:3,k:'capital'},{city:'Wellington',country:'New Zealand',lat:-41.28270,lng:174.77642,h:20,d:3,k:'capital'},
{city:'New York',country:'United States',lat:40.75818,lng:-73.98510,h:55,d:1,k:'major',famous:1},{city:'Barcelona',country:'Spain',lat:41.40346,lng:2.17397,h:40,d:1,k:'major',famous:1},{city:'Amsterdam',country:'Netherlands',lat:52.37432,lng:4.89518,h:185,d:1,k:'major',famous:1},{city:'Sydney',country:'Australia',lat:-33.86114,lng:151.21056,h:35,d:1,k:'major',famous:1},{city:'San Francisco',country:'United States',lat:37.80766,lng:-122.47524,h:295,d:1,k:'major',famous:1},{city:'Dubai',country:'United Arab Emirates',lat:25.19700,lng:55.27430,h:20,d:1,k:'major',famous:1},{city:'Singapore',country:'Singapore',lat:1.28390,lng:103.86090,h:45,d:1,k:'major',famous:1},{city:'Toronto',country:'Canada',lat:43.65509,lng:-79.38025,h:5,d:2,k:'major'},{city:'Mexico City',country:'Mexico',lat:19.42724,lng:-99.16765,h:65,d:2,k:'major'},{city:'Buenos Aires',country:'Argentina',lat:-34.60366,lng:-58.38171,h:10,d:2,k:'major'},{city:'Cape Town',country:'South Africa',lat:-33.92432,lng:18.41578,h:15,d:2,k:'major'},{city:'Auckland',country:'New Zealand',lat:-36.85092,lng:174.76452,h:5,d:2,k:'major'},{city:'Busan',country:'South Korea',lat:35.15768,lng:129.05930,h:210,d:3,k:'city'},{city:'Porto',country:'Portugal',lat:41.14480,lng:-8.61035,h:185,d:3,k:'city'},{city:'Adelaide',country:'Australia',lat:-34.92281,lng:138.60477,h:95,d:3,k:'city'},{city:'Curitiba',country:'Brazil',lat:-25.42965,lng:-49.27133,h:85,d:3,k:'city'},{city:'Kaohsiung',country:'Taiwan',lat:22.61395,lng:120.30498,h:25,d:3,k:'city'},{city:'Sapporo',country:'Japan',lat:43.06064,lng:141.35439,h:90,d:3,k:'city'},{city:'Malmö',country:'Sweden',lat:55.60549,lng:13.00355,h:175,d:3,k:'city'},{city:'Zaragoza',country:'Spain',lat:41.64984,lng:-0.88233,h:350,d:3,k:'city'},{city:'Thessaloniki',country:'Greece',lat:40.63690,lng:22.94412,h:90,d:3,k:'city'},{city:'Ghent',country:'Belgium',lat:51.05439,lng:3.72197,h:190,d:3,k:'city'},
{city:'Great Ocean Road',country:'Australia',lat:-38.66404,lng:143.10446,h:250,d:2,k:'scenic'},{city:'Iceland Ring Road',country:'Iceland',lat:63.61664,lng:-19.98891,h:95,d:2,k:'scenic'},{city:'Tuscany',country:'Italy',lat:43.31808,lng:11.33082,h:120,d:2,k:'scenic'},{city:'Lofoten',country:'Norway',lat:68.20824,lng:13.50518,h:75,d:2,k:'scenic'},{city:'Lake Tekapo',country:'New Zealand',lat:-44.00474,lng:170.47768,h:40,d:2,k:'scenic'},{city:'Canadian Rockies',country:'Canada',lat:51.17770,lng:-115.57160,h:300,d:2,k:'scenic'},{city:'Patagonia',country:'Argentina',lat:-50.33766,lng:-72.26490,h:20,d:3,k:'remote'},{city:'Namib Road',country:'Namibia',lat:-24.74844,lng:15.30044,h:140,d:3,k:'remote'},{city:'Faroe Islands',country:'Faroe Islands',lat:62.01945,lng:-6.77128,h:10,d:3,k:'scenic'},{city:'Scottish Highlands',country:'United Kingdom',lat:57.10210,lng:-4.69042,h:240,d:3,k:'scenic'},{city:'Atacama approach',country:'Chile',lat:-22.90650,lng:-68.19870,h:45,d:3,k:'remote'},{city:'Arizona desert road',country:'United States',lat:35.13585,lng:-111.26010,h:110,d:3,k:'remote'}
];
const formats={classic:{name:'Classic',rounds:5,seconds:90,ranked:false},sprint:{name:'Sprint',rounds:5,seconds:35,ranked:false},duel:{name:'League Duel',rounds:5,seconds:60,ranked:true},endurance:{name:'Endurance',rounds:10,seconds:120,ranked:false}};
const pools={smart:{name:'Smart Random',summary:'Balanced world mix with weighted probability'},cities:{name:'Cities Only',summary:'Capitals, major and secondary cities'},capitals:{name:'Capitals',summary:'National capitals and recognizable centres'},famous:{name:'Famous Places',summary:'Landmarks and globally known districts'},megacities:{name:'Megacities',summary:'Dense metropolitan streets'},scenic:{name:'Scenic Roads',summary:'Coasts, mountains and countryside'}};
const difficulties={1:{name:'Easy',summary:'Clear clues and famous locations',reward:1},2:{name:'Medium',summary:'Fewer obvious clues',reward:1.2},3:{name:'Hard',summary:'Subtle clues and less familiar places',reward:1.5}};
const rivals=[{id:'nova',name:'Nova',flag:'NO',skill:.78},{id:'atlas',name:'Atlas',flag:'DE',skill:.70},{id:'mira',name:'Mira',flag:'JP',skill:.63},{id:'roam',name:'Roam',flag:'BR',skill:.55}];
const $=id=>document.getElementById(id),screens=['home','game','result','final'];
let selectedFormat='classic',selectedPool='smart',selectedDifficulty=1,match=[],roundIndex=0,guess=null,guessMap=null,resultMap=null,guessMarker=null,timerId=null,seconds=0,totalSeconds=0,scores={you:0,nova:0,atlas:0,mira:0,roam:0},profile=loadProfile();
function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id))}
function key(){return String(window.GEOSCOPE_CONFIG?.googleMapsApiKey||'').trim()}
function loadProfile(){try{return JSON.parse(localStorage.getItem('geoscopeArenaProfile')||'null')||{xp:0,coins:0,wins:0}}catch(_){return{xp:0,coins:0,wins:0}}}
function saveProfile(){try{localStorage.setItem('geoscopeArenaProfile',JSON.stringify(profile))}catch(_){}}
function leagueFor(xp){if(xp<1000)return{name:'Bronze III',short:'III',base:0,next:1000,c1:'#6f4e38',c2:'#bf8a5f'};if(xp<2500)return{name:'Silver II',short:'II',base:1000,next:2500,c1:'#68727b',c2:'#d2d7db'};if(xp<5000)return{name:'Gold I',short:'I',base:2500,next:5000,c1:'#986913',c2:'#ffd56a'};if(xp<8000)return{name:'Platinum',short:'P',base:5000,next:8000,c1:'#2b7873',c2:'#78dfd4'};return{name:'Diamond',short:'D',base:8000,next:13000,c1:'#355e91',c2:'#8ac8ff'}}
function renderProfile(){const l=leagueFor(profile.xp),pct=Math.max(0,Math.min(100,(profile.xp-l.base)/(l.next-l.base)*100));$('leagueTop').textContent=l.name.toUpperCase();$('coinsTop').textContent=profile.coins.toLocaleString();$('leagueName').textContent=l.name;$('leagueBadge').textContent=l.short;$('leagueBadge').style.background=`linear-gradient(145deg,${l.c1},${l.c2})`;$('xpText').textContent=`${profile.xp.toLocaleString()} / ${l.next.toLocaleString()} XP`;$('xpFill').style.width=pct+'%';$('winsText').textContent=`${profile.wins} match win${profile.wins===1?'':'s'}`}
function participants(){return[{id:'you',name:'You',flag:'YOU',skill:1},...rivals]}
function standings(){return participants().map(p=>({...p,score:scores[p.id]||0})).sort((a,b)=>b.score-a.score)}
function renderRoster(){$('homeRoster').innerHTML=participants().map(p=>`<div class="player ${p.id==='you'?'me':''}"><div class="avatar">${p.flag}</div><div><b>${p.name}</b><small>${p.id==='you'?'CURRENT PLAYER':'AI RIVAL'}</small></div><strong>${p.id==='you'?'READY':'ONLINE'}</strong></div>`).join('')}
function renderMini(){$('miniBoard').innerHTML=standings().map((p,i)=>`<div class="mini-row ${p.id==='you'?'me':''}"><span>${i+1}</span><span>${p.name}</span><b>${p.score.toLocaleString()}</b></div>`).join('')}
function renderStandings(target){$(target).innerHTML=standings().map((p,i)=>`<div class="standing ${p.id==='you'?'me':''}"><b>${i+1}</b><span>${p.name}${p.id==='you'?' · YOU':' · AI'}</span><strong>${p.score.toLocaleString()}</strong></div>`).join('')}
function updateSelectionText(){$('poolSummary').textContent=pools[selectedPool].summary;$('difficultySummary').textContent=`${difficulties[selectedDifficulty].summary} · ${difficulties[selectedDifficulty].reward}× rewards`;$('rewardMultiplier').textContent=difficulties[selectedDifficulty].reward+'×'}
function difficultyWeight(item){const delta=Math.abs(item.d-selectedDifficulty);return delta===0?7:delta===1?1.8:.25}
function poolWeight(item){if(selectedPool==='cities')return['capital','major','city'].includes(item.k)?1:0;if(selectedPool==='capitals')return item.k==='capital'?1:0;if(selectedPool==='famous')return item.famous?1:0;if(selectedPool==='megacities')return item.k==='major'?1:0;if(selectedPool==='scenic')return ['scenic','remote'].includes(item.k)?1:0;return{capital:3.4,major:5,city:4,scenic:1.4,remote:.35}[item.k]||1}
function weightedSample(count){const remaining=[...locations],picked=[];while(picked.length<count&&remaining.length){const weights=remaining.map(x=>poolWeight(x)*difficultyWeight(x)),total=weights.reduce((a,b)=>a+b,0);if(total<=0)break;let roll=Math.random()*total,index=0;for(;index<weights.length;index++){roll-=weights[index];if(roll<=0)break}picked.push(remaining.splice(Math.min(index,remaining.length-1),1)[0])}return picked}
function mapUrl(loc){const q=new URLSearchParams({key:key(),location:`${loc.lat},${loc.lng}`,heading:String(loc.h||0),pitch:'0',fov:'90',radius:'120',source:'outdoor'});return'https://www.google.com/maps/embed/v1/streetview?'+q.toString()}
function startMatch(){if(!key()){$('ownerNotice').hidden=false;return}const f=formats[selectedFormat];match=weightedSample(f.rounds);if(match.length<f.rounds){alert('Not enough locations for this combination. Choose another location set or difficulty.');return}roundIndex=0;guess=null;scores={you:0,nova:0,atlas:0,mira:0,roam:0};show('game');startRound()}
function startRound(){clearInterval(timerId);guess=null;const f=formats[selectedFormat],loc=match[roundIndex];$('submitGuess').disabled=true;$('coords').textContent='Click anywhere on the map';$('guessTip').textContent='Zoom in for a more precise guess';$('guessPanel').classList.remove('open');if(guessMarker){guessMarker.remove();guessMarker=null}if(guessMap)guessMap.jumpTo({center:[0,20],zoom:1.7});$('gameModeLabel').textContent=`${f.name.toUpperCase()} · ${pools[selectedPool].name.toUpperCase()}`;$('roundLabel').textContent=`ROUND ${roundIndex+1} / ${match.length}`;$('roundProgress').style.width=`${((roundIndex+1)/match.length)*100}%`;$('streetView').src=mapUrl(loc);totalSeconds=f.seconds;seconds=f.seconds;updateTimer();timerId=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timerId);if(!guess)guess={lat:0,lng:0};finishRound(true)}},1000);renderMini();showIntro()}
function showIntro(){$('introMode').textContent=pools[selectedPool].name.toUpperCase();$('introRound').textContent=`ROUND ${roundIndex+1}`;$('introDifficulty').textContent=difficulties[selectedDifficulty].name.toUpperCase();const el=$('roundIntro');el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function updateTimer(){const m=Math.floor(seconds/60),s=seconds%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('timer').style.color=seconds<=10?'var(--red)':'var(--green)'}
function markerElement(cls){const el=document.createElement('div');el.className=cls;return el}
function ensureGuessMap(){if(guessMap)return;if(!window.maplibregl){alert('The map renderer did not load. Refresh the page.');return}guessMap=new maplibregl.Map({container:'guessMap',style:MAP_STYLE,center:[0,20],zoom:1.7,attributionControl:true});guessMap.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');guessMap.on('click',e=>{guess={lat:e.lngLat.lat,lng:e.lngLat.lng};if(guessMarker)guessMarker.remove();guessMarker=new maplibregl.Marker({element:markerElement('guess-marker')}).setLngLat([guess.lng,guess.lat]).addTo(guessMap);$('coords').textContent=`${Math.abs(guess.lat).toFixed(2)}° ${guess.lat>=0?'N':'S'}, ${Math.abs(guess.lng).toFixed(2)}° ${guess.lng>=0?'E':'W'}`;$('guessTip').textContent='Pin placed · submit when ready';$('submitGuess').disabled=false})}
function openMap(){ensureGuessMap();if(!guessMap)return;$('guessPanel').classList.add('open');setTimeout(()=>guessMap.resize(),280)}
function distanceKm(a,b,c,d){const r=x=>x*Math.PI/180,R=6371,dy=r(c-a),dx=r(d-b),h=Math.sin(dy/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dx/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function calculateScore(km){const distanceScore=Math.max(0,Math.round(4500*Math.exp(-km/1750))),accuracy=distanceScore/4500,timeRatio=Math.max(0,seconds/totalSeconds),speedScore=Math.round(500*Math.pow(timeRatio,.65)*(.3+.7*accuracy));return{distanceScore,speedScore,total:Math.min(5000,distanceScore+speedScore)}}
function finishRound(timeout){if(!guess)return;clearInterval(timerId);const loc=match[roundIndex],km=distanceKm(guess.lat,guess.lng,loc.lat,loc.lng),parts=calculateScore(km);scores.you+=parts.total;const penalty=(selectedDifficulty-1)*160;rivals.forEach(p=>{const base=2100+p.skill*2250-penalty,variance=(Math.random()-.5)*1700,bonus=selectedFormat==='duel'?200:0;scores[p.id]+=Math.max(120,Math.min(5000,Math.round(base+variance+bonus)))});$('resultRoundLabel').textContent=`ROUND ${roundIndex+1} COMPLETE`;$('resultTitle').textContent=parts.total>4400?'Excellent read.':parts.total>3200?'Strong guess.':parts.total>1800?'You found the region.':'The world is difficult.';$('distanceValue').textContent=km<1?`${Math.round(km*1000)} m`:`${Math.round(km).toLocaleString()} km`;$('locationName').textContent=`${loc.city}, ${loc.country}${timeout?' · time expired':''}`;$('distanceScore').textContent=parts.distanceScore.toLocaleString();$('speedScore').textContent=parts.speedScore.toLocaleString();$('timeUsed').textContent=(totalSeconds-seconds)+'s';$('timeRemaining').textContent=seconds+'s left';renderStandings('roundStandings');show('result');renderResultMap(loc);animateNumber($('roundScore'),parts.total,650)}
function renderResultMap(loc){if(resultMap){resultMap.remove();resultMap=null}resultMap=new maplibregl.Map({container:'resultMap',style:MAP_STYLE,center:[0,20],zoom:1.4,attributionControl:true});resultMap.on('load',()=>{new maplibregl.Marker({element:markerElement('actual-marker')}).setLngLat([loc.lng,loc.lat]).addTo(resultMap);new maplibregl.Marker({element:markerElement('guess-marker')}).setLngLat([guess.lng,guess.lat]).addTo(resultMap);resultMap.addSource('answer-line',{type:'geojson',data:{type:'Feature',geometry:{type:'LineString',coordinates:[[guess.lng,guess.lat],[loc.lng,loc.lat]]}}});resultMap.addLayer({id:'answer-line',type:'line',source:'answer-line',paint:{'line-color':'#c9ff46','line-width':3,'line-dasharray':[2,2]}});const bounds=new maplibregl.LngLatBounds().extend([guess.lng,guess.lat]).extend([loc.lng,loc.lat]);resultMap.fitBounds(bounds,{padding:{top:110,right:470,bottom:80,left:80},maxZoom:7,duration:1300})})}
function animateNumber(el,value,duration){const start=performance.now();function step(now){const p=Math.min(1,(now-start)/duration),e=1-Math.pow(1-p,3);el.textContent=Math.round(value*e).toLocaleString();if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
function nextRound(){roundIndex++;if(roundIndex>=match.length){finishMatch();return}show('game');startRound()}
function finishMatch(){const board=standings(),rank=board.findIndex(p=>p.id==='you')+1,total=scores.you,m=difficulties[selectedDifficulty].reward,xp=Math.round((total/55+(6-rank)*40+(selectedFormat==='duel'?120:0))*m),coins=Math.round((total/310+(6-rank)*8)*m);profile.xp+=xp;profile.coins+=coins;if(rank===1)profile.wins++;saveProfile();$('finishPlace').textContent=`${rank}${rank===1?'ST':rank===2?'ND':rank===3?'RD':'TH'} PLACE`;$('xpReward').textContent='+'+xp.toLocaleString();$('coinReward').textContent='+'+coins.toLocaleString();$('badgeReward').textContent=rank===1?'★':'◆';renderStandings('finalBoard');renderProfile();show('final');animateNumber($('totalScore'),total,850)}
$('formats').addEventListener('click',e=>{const b=e.target.closest('[data-format]');if(!b)return;selectedFormat=b.dataset.format;document.querySelectorAll('[data-format]').forEach(x=>x.classList.toggle('active',x===b))});
$('pools').addEventListener('click',e=>{const b=e.target.closest('[data-pool]');if(!b)return;selectedPool=b.dataset.pool;document.querySelectorAll('[data-pool]').forEach(x=>x.classList.toggle('active',x===b));updateSelectionText()});
$('difficulties').addEventListener('click',e=>{const b=e.target.closest('[data-difficulty]');if(!b)return;selectedDifficulty=Number(b.dataset.difficulty);document.querySelectorAll('[data-difficulty]').forEach(x=>x.classList.toggle('active',x===b));updateSelectionText()});
$('startBtn').addEventListener('click',startMatch);$('againBtn').addEventListener('click',startMatch);$('homeBtn').addEventListener('click',()=>show('home'));$('mapTrigger').addEventListener('click',openMap);$('closeMap').addEventListener('click',()=>$('guessPanel').classList.remove('open'));$('submitGuess').addEventListener('click',()=>finishRound(false));$('nextRound').addEventListener('click',nextRound);document.addEventListener('keydown',e=>{if(e.key==='Escape')$('guessPanel').classList.remove('open')});
renderProfile();renderRoster();updateSelectionText();if(!key()){$('ownerNotice').hidden=false;$('startBtn').disabled=true}
})();
