(() => {
'use strict';
const $ = id => document.getElementById(id);
const $$ = selector => Array.from(document.querySelectorAll(selector));
const I18N = window.GeoScopeI18n;
const LANGS = I18N.languageNames;
const FORMAT_ASSETS = {
  classic:{icon:'⌖',image:'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=86'},
  sprint:{icon:'⚡',image:'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=1000&q=86'},
  duel:{icon:'⚔',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=86'},
  endurance:{icon:'▲',image:'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1000&q=86'}
};
const POOL_ASSETS = {
  smart:{icon:'◎',image:'https://images.unsplash.com/photo-1522083165195-3424ed129620?auto=format&fit=crop&w=900&q=86'},
  cities:{icon:'▦',image:'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=900&q=86'},
  capitals:{icon:'◆',image:'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=86'},
  famous:{icon:'★',image:'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=900&q=86'},
  megacities:{icon:'▥',image:'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=86'},
  scenic:{icon:'⌁',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=86'}
};
const DIFFICULTY_ASSETS = {
  1:{icon:'Ⅰ',image:'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=900&q=86'},
  2:{icon:'Ⅱ',image:'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=900&q=86'},
  3:{icon:'Ⅲ',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=86'}
};
let user = readJson('geoShellUser', null);
let cfg = Object.assign({format:'classic',pool:'smart',difficulty:1,lang:defaultLanguage()}, readJson('geoCfg', {}));
let profile = Object.assign({matches:0,wins:0,totalScore:0,best:0,rounds:0,countryHits:0,totalKm:0,totalTime:0,history:[],choices:{},coins:248}, readJson('geoProProfile', {}));
let googleReady = false;
function defaultLanguage(){const code=(navigator.language||'en').slice(0,2);return LANGS[code]?code:'en'}
function t(key,vars){return I18N.t(cfg.lang,key,vars)}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch(_){}}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function initials(name){return String(name||'GeoScope Player').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'GP'}
function showToast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function applyLanguage(){document.documentElement.lang=cfg.lang;document.documentElement.dir=cfg.lang==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));['landingLanguage','appLanguage'].forEach(id=>{if($(id))$(id).value=cfg.lang});renderModeCards();renderSelectionCards();renderProfileData();renderHub();const active=$('.app-view.active');if(active)updateViewTitle(active.id.replace('view-',''))}
function setupLanguageSelects(){['landingLanguage','appLanguage'].forEach(id=>{const select=$(id);select.innerHTML='';Object.entries(LANGS).forEach(([code,label])=>select.add(new Option(label,code)));select.value=cfg.lang;select.onchange=e=>{cfg.lang=e.target.value;writeJson('geoCfg',cfg);applyLanguage();if(window.google?.accounts?.id)configureGoogle()}})}
function openAuth(){const auth=$('auth');auth.classList.add('active');auth.setAttribute('aria-hidden','false');$('playerName').value=user?.name||'';setTimeout(()=>$('playerName').focus(),120)}
function closeAuth(){$('auth').classList.remove('active');$('auth').setAttribute('aria-hidden','true')}
function showLanding(){location.hash='';$('landing').classList.remove('hidden');$('app').classList.remove('active');closeAuth();window.scrollTo({top:0,behavior:'smooth'})}
function enterApp(view='hub'){if(!user){openAuth();return}$('landing').classList.add('hidden');$('app').classList.add('active');closeAuth();location.hash='app';hydrateUser();profile=Object.assign(profile,readJson('geoProProfile',{}));renderProfileData();showView(view);window.scrollTo(0,0)}
function updateViewTitle(view){const keys={hub:'nav.home',play:'nav.play',competitive:'nav.competitive',social:'nav.social',profile:'nav.profile'};$('viewTitle').textContent=t(keys[view]||'nav.home')}
function showView(view){$$('.app-view').forEach(el=>el.classList.toggle('active',el.id===`view-${view}`));$$('.nav-btn[data-app-view]').forEach(el=>el.classList.toggle('active',el.dataset.appView===view));updateViewTitle(view);if(view==='profile')renderProfileData();window.scrollTo({top:0,behavior:'smooth'})}
function hydrateUser(){const name=user?.name||t('auth.placeholder'),mark=initials(name);['sideName','leaderName','profileName'].forEach(id=>{if($(id))$(id).textContent=name});['sideAvatar','profileAvatar'].forEach(id=>{if($(id))$(id).textContent=mark});$('coinValue').textContent=Number(profile.coins||248).toLocaleString(cfg.lang);$('welcomeName').textContent=t('hub.greeting',{name:name.split(' ')[0]})}
function completeLocalLogin(){const name=$('playerName').value.trim()||t('auth.placeholder');user={name,provider:'local',createdAt:new Date().toISOString()};writeJson('geoShellUser',user);enterApp('hub');showToast(t('toast.welcome',{name}))}
function decodeJwt(token){try{const part=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(decodeURIComponent(atob(part).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join('')))}catch{return null}}
function handleGoogleCredential(response){const data=decodeJwt(response.credential);if(!data){showToast(t('toast.googleError'));return}user={name:data.name||data.given_name||t('auth.placeholder'),email:data.email||'',picture:data.picture||'',provider:'google',createdAt:new Date().toISOString()};writeJson('geoShellUser',user);enterApp('hub');showToast(t('toast.googleWelcome'))}
function configureGoogle(){const clientId=String(window.GEOSCOPE_AUTH_CONFIG?.googleClientId||'').trim();if(!clientId||!window.google?.accounts?.id)return false;try{google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential,auto_select:false,cancel_on_tap_outside:true});const host=$('googleButtonHost');host.innerHTML='';google.accounts.id.renderButton(host,{theme:'outline',size:'large',width:420,text:'continue_with',shape:'rectangular',locale:cfg.lang});googleReady=true;return true}catch(error){console.error(error);return false}}
function signOut(){localStorage.removeItem('geoShellUser');user=null;showLanding();showToast(t('toast.signedOut'))}
function renderModeCards(){$('landingModeCards').innerHTML=['classic','sprint','duel','endurance'].map(key=>{const a=FORMAT_ASSETS[key];return `<article class="landing-mode-card reveal visible" style="background-image:url('${a.image}')"><div><span class="feature-icon">${a.icon}</span><span class="mode-tag">${escapeHtml(t(`format.${key}.tag`))}</span><h3>${escapeHtml(t(`format.${key}.name`))}</h3><p>${escapeHtml(t(`format.${key}.desc`))}</p></div></article>`}).join('')}
function choiceCard(type,key,asset,active){return `<button class="choice-card ${active?'active':''}" data-${type}="${key}"><div class="choice-image" style="background-image:url('${asset.image}')"><span class="choice-icon">${asset.icon}</span></div><div class="choice-copy">${type==='format'?`<small>${escapeHtml(t(`format.${key}.tag`))}</small>`:''}<b>${escapeHtml(t(`${type}.${key}.name`))}</b><p>${escapeHtml(t(`${type}.${key}.desc`))}</p></div></button>`}
function renderSelectionCards(){$('formatChoices').innerHTML=Object.keys(FORMAT_ASSETS).map(key=>choiceCard('format',key,FORMAT_ASSETS[key],cfg.format===key)).join('');$('poolChoices').innerHTML=Object.keys(POOL_ASSETS).map(key=>choiceCard('pool',key,POOL_ASSETS[key],cfg.pool===key)).join('');$('difficultyChoices').innerHTML=Object.keys(DIFFICULTY_ASSETS).map(key=>choiceCard('difficulty',key,DIFFICULTY_ASSETS[key],Number(cfg.difficulty)===Number(key))).join('');updateSetupSummary()}
function updateSetupSummary(){const format=t(`format.${cfg.format}.name`),pool=t(`pool.${cfg.pool}.name`),difficulty=t(`difficulty.${cfg.difficulty}.name`);$('summaryFormat').textContent=format;$('summaryPool').textContent=pool;$('summaryDifficulty').textContent=difficulty;$('launchTitle').textContent=`${format} · ${pool}`;$('launchDescription').textContent=t(`format.${cfg.format}.desc`);$('launchIcon').textContent=FORMAT_ASSETS[cfg.format].icon;$('launchPreview').style.backgroundImage=`url('${POOL_ASSETS[cfg.pool].image}')`;writeJson('geoCfg',cfg)}
function profileNumbers(){const rounds=Number(profile.rounds||0),matches=Number(profile.matches||0);return{matches,wins:Number(profile.wins||0),best:Number(profile.best||0),avgScore:matches?Math.round(Number(profile.totalScore||0)/matches):0,country:rounds?Math.round(Number(profile.countryHits||0)/rounds*100):0,avgKm:rounds?Math.round(Number(profile.totalKm||0)/rounds):0,avgTime:rounds?Math.round(Number(profile.totalTime||0)/rounds):0,rounds}}
function renderHub(){const n=profileNumbers();$('recentFormValue').textContent=n.matches?`${n.avgScore.toLocaleString(cfg.lang)} · ${n.country}%`:'—';if(user)hydrateUser()}
function renderProfileData(){if(!$('profileStats'))return;profile=Object.assign(profile,readJson('geoProProfile',{}));const n=profileNumbers();const stats=[['stats.matches',n.matches],['stats.wins',n.wins],['stats.best',n.best.toLocaleString(cfg.lang)],['stats.average',n.avgScore.toLocaleString(cfg.lang)],['stats.country',`${n.country}%`],['stats.distance',`${n.avgKm.toLocaleString(cfg.lang)} km`],['stats.time',`${n.avgTime}s`],['stats.rounds',n.rounds]];$('profileStats').innerHTML=stats.map(([label,value])=>`<article class="stat-card surface"><b>${value}</b><span>${escapeHtml(t(label))}</span></article>`).join('');const history=Array.isArray(profile.history)?profile.history.slice(0,8):[];$('profileHistory').innerHTML=history.length?history.map(item=>`<div class="history-row"><div><b>${escapeHtml(t(`format.${item.format}.name`)||item.format)} · ${escapeHtml(t(`pool.${item.pool}.name`)||item.pool)}</b><small>${new Date(item.date||Date.now()).toLocaleDateString(cfg.lang)} · ${item.rounds||0} ${escapeHtml(t('common.rounds'))}</small></div><strong>${Number(item.score||0).toLocaleString(cfg.lang)}</strong></div>`).join(''):`<div class="history-row"><div><b>${escapeHtml(t('profile.noMatches'))}</b><small>${escapeHtml(t('profile.noMatchesDesc'))}</small></div><strong>—</strong></div>`;const prefs=Object.entries(profile.choices||{}).sort((a,b)=>b[1]-a[1]).slice(0,6);$('profilePreferences').innerHTML=prefs.length?prefs.map(([key,count])=>{const label=FORMAT_ASSETS[key]?t(`format.${key}.name`):POOL_ASSETS[key]?t(`pool.${key}.name`):key;return `<div class="history-row"><div><b>${escapeHtml(label)}</b><small>${escapeHtml(t('profile.selectedTimes',{count}))}</small></div><strong>${count}</strong></div>`}).join(''):`<div class="history-row"><div><b>${escapeHtml(t(`format.${cfg.format}.name`))}</b><small>${escapeHtml(t('profile.currentPreference'))}</small></div><strong>${escapeHtml(t(`pool.${cfg.pool}.name`))}</strong></div>`;const heat=$('activityHeatmap');heat.innerHTML='';for(let i=0;i<84;i++){const cell=document.createElement('i');cell.title=t('profile.activityDay',{day:i+1});heat.appendChild(cell)}renderHub()}
function launchGame(overrides={}){cfg=Object.assign(cfg,overrides);writeJson('geoCfg',cfg);const params=new URLSearchParams({autostart:'1',return:'app',format:cfg.format,pool:cfg.pool,difficulty:String(cfg.difficulty),lang:cfg.lang});location.href=`arena-pro.html?${params.toString()}`}
function bindEvents(){$$('[data-open-auth]').forEach(el=>el.addEventListener('click',openAuth));$$('[data-enter-app]').forEach(el=>el.addEventListener('click',()=>enterApp('hub')));$$('[data-scroll-top]').forEach(el=>el.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'})));$('authClose').onclick=closeAuth;$('guestLogin').onclick=completeLocalLogin;$('playerName').addEventListener('keydown',e=>{if(e.key==='Enter')completeLocalLogin()});$('googleFallback').onclick=()=>googleReady?google.accounts.id.prompt():$('oauthModal').classList.add('open');$$('[data-close-modal]').forEach(el=>el.onclick=()=>el.closest('.modal').classList.remove('open'));$('oauthGuest').onclick=()=>{$('oauthModal').classList.remove('open');$('playerName').focus()};$$('[data-app-view]').forEach(el=>el.addEventListener('click',()=>showView(el.dataset.appView)));$('backToLanding').onclick=showLanding;$('signOut').onclick=signOut;$('formatChoices').onclick=e=>{const b=e.target.closest('[data-format]');if(!b)return;cfg.format=b.dataset.format;renderSelectionCards()};$('poolChoices').onclick=e=>{const b=e.target.closest('[data-pool]');if(!b)return;cfg.pool=b.dataset.pool;renderSelectionCards()};$('difficultyChoices').onclick=e=>{const b=e.target.closest('[data-difficulty]');if(!b)return;cfg.difficulty=Number(b.dataset.difficulty);renderSelectionCards()};$('launchGame').onclick=()=>launchGame();$$('[data-quick-duel]').forEach(el=>el.onclick=()=>launchGame({format:'duel',pool:'smart',difficulty:2}));$$('[data-launch-daily]').forEach(el=>el.onclick=()=>launchGame({format:'classic',pool:'smart',difficulty:2}));$$('[data-demo-action]').forEach(el=>el.onclick=()=>showToast(t('toast.backend')));window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeAuth();$('oauthModal').classList.remove('open')}})}
function setupMotion(){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});$$('.reveal').forEach(el=>observer.observe(el));$$('.feature-card,.landing-mode-card,.dash-card,.choice-card').forEach(card=>{card.addEventListener('pointermove',e=>{if(window.innerWidth<900)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${y*-2.5}deg) rotateY(${x*3.5}deg) translateY(-5px)`});card.addEventListener('pointerleave',()=>card.style.transform='')})}
function restoreRoute(){if(location.hash==='#app'){if(user)enterApp('hub');else openAuth()}}
function init(){setupLanguageSelects();bindEvents();renderModeCards();renderSelectionCards();applyLanguage();setupMotion();renderProfileData();if(user)hydrateUser();const googlePoll=setInterval(()=>{if(configureGoogle()||document.readyState==='complete')clearInterval(googlePoll)},250);setTimeout(()=>clearInterval(googlePoll),5000);restoreRoute()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
