(function(){
'use strict';
const locations=[
{level:'easy',name:'Times Square',city:'New York',country:'United States',lat:40.75818,lng:-73.98510,h:55},{level:'easy',name:'Eiffel Tower district',city:'Paris',country:'France',lat:48.85878,lng:2.29918,h:270},{level:'easy',name:'Westminster Bridge',city:'London',country:'United Kingdom',lat:51.50079,lng:-0.12228,h:275},{level:'easy',name:'Shibuya Crossing',city:'Tokyo',country:'Japan',lat:35.65946,lng:139.70055,h:25},{level:'easy',name:'Colosseum district',city:'Rome',country:'Italy',lat:41.89093,lng:12.49155,h:205},{level:'easy',name:'Brandenburg Gate',city:'Berlin',country:'Germany',lat:52.51651,lng:13.37908,h:265},{level:'easy',name:'Sagrada Família',city:'Barcelona',country:'Spain',lat:41.40347,lng:2.17398,h:40},{level:'easy',name:'Damrak',city:'Amsterdam',country:'Netherlands',lat:52.37432,lng:4.89518,h:185},{level:'easy',name:'Circular Quay',city:'Sydney',country:'Australia',lat:-33.86114,lng:151.21056,h:35},{level:'easy',name:'White House district',city:'Washington',country:'United States',lat:38.89736,lng:-77.03651,h:195},{level:'easy',name:'Puerta del Sol',city:'Madrid',country:'Spain',lat:40.41693,lng:-3.70339,h:130},{level:'easy',name:'Senate Square',city:'Helsinki',country:'Finland',lat:60.16963,lng:24.95183,h:120},
{level:'medium',name:'Avenida da Liberdade',city:'Lisbon',country:'Portugal',lat:38.72091,lng:-9.14595,h:350},{level:'medium',name:'Ringstrasse',city:'Vienna',country:'Austria',lat:48.20451,lng:16.36108,h:85},{level:'medium',name:'Nyhavn district',city:'Copenhagen',country:'Denmark',lat:55.68001,lng:12.58804,h:250},{level:'medium',name:'Norrmalm',city:'Stockholm',country:'Sweden',lat:59.33242,lng:18.06489,h:55},{level:'medium',name:'Karl Johans gate',city:'Oslo',country:'Norway',lat:59.91351,lng:10.73920,h:80},{level:'medium',name:'Wenceslas Square',city:'Prague',country:'Czechia',lat:50.08102,lng:14.42566,h:320},{level:'medium',name:'Andrássy Avenue',city:'Budapest',country:'Hungary',lat:47.50244,lng:19.05954,h:55},{level:'medium',name:'Paseo de la Reforma',city:'Mexico City',country:'Mexico',lat:19.42724,lng:-99.16765,h:65},{level:'medium',name:'Gwanghwamun',city:'Seoul',country:'South Korea',lat:37.57210,lng:126.97677,h:5},{level:'medium',name:'Orchard Road',city:'Singapore',country:'Singapore',lat:1.30485,lng:103.83191,h:115},{level:'medium',name:'Yonge Street',city:'Toronto',country:'Canada',lat:43.65509,lng:-79.38025,h:5},{level:'medium',name:'Obelisk district',city:'Buenos Aires',country:'Argentina',lat:-34.60366,lng:-58.38171,h:10},{level:'medium',name:'Long Street',city:'Cape Town',country:'South Africa',lat:-33.92432,lng:18.41578,h:15},{level:'medium',name:'Syntagma district',city:'Athens',country:'Greece',lat:37.97521,lng:23.73493,h:130},{level:'medium',name:'Queen Street',city:'Auckland',country:'New Zealand',lat:-36.85092,lng:174.76452,h:5},
{level:'hard',name:'Ribeira approach',city:'Porto',country:'Portugal',lat:41.14480,lng:-8.61035,h:185},{level:'hard',name:'Rundle Street',city:'Adelaide',country:'Australia',lat:-34.92281,lng:138.60477,h:95},{level:'hard',name:'Rua XV de Novembro',city:'Curitiba',country:'Brazil',lat:-25.42965,lng:-49.27133,h:85},{level:'hard',name:'Sanduo district',city:'Kaohsiung',country:'Taiwan',lat:22.61395,lng:120.30498,h:25},{level:'hard',name:'Odori district',city:'Sapporo',country:'Japan',lat:43.06064,lng:141.35439,h:90},{level:'hard',name:'Central Malmö',city:'Malmö',country:'Sweden',lat:55.60549,lng:13.00355,h:175},{level:'hard',name:'Paseo Independencia',city:'Zaragoza',country:'Spain',lat:41.64984,lng:-0.88233,h:350},{level:'hard',name:'Egnatia Street',city:'Thessaloniki',country:'Greece',lat:40.63690,lng:22.94412,h:90},{level:'hard',name:'Korenmarkt district',city:'Ghent',country:'Belgium',lat:51.05439,lng:3.72197,h:190},{level:'hard',name:'18 de Julio Avenue',city:'Montevideo',country:'Uruguay',lat:-34.90627,lng:-56.19172,h:80},{level:'hard',name:'Lambton Quay',city:'Wellington',country:'New Zealand',lat:-41.28270,lng:174.77642,h:20},{level:'hard',name:'Jasper Avenue',city:'Edmonton',country:'Canada',lat:53.54135,lng:-113.49396,h:270},{level:'hard',name:'Seomyeon district',city:'Busan',country:'South Korea',lat:35.15768,lng:129.05930,h:210},{level:'hard',name:'Slovenska cesta',city:'Ljubljana',country:'Slovenia',lat:46.05292,lng:14.50377,h:5},{level:'hard',name:'Rotermann district',city:'Tallinn',country:'Estonia',lat:59.43858,lng:24.75769,h:270}
];
const modes={classic:{name:'World Classic',rounds:5,seconds:90,ranked:false},sprint:{name:'World Sprint',rounds:5,seconds:35,ranked:false},duel:{name:'League Duel',rounds:5,seconds:60,ranked:true},endurance:{name:'Endurance',rounds:10,seconds:120,ranked:false}};
const levels={easy:{name:'Easy',description:'Capitals and famous landmarks',reward:1},medium:{name:'Medium',description:'Major cities with fewer obvious clues',reward:1.2},hard:{name:'Hard',description:'Secondary cities and subtle urban clues',reward:1.5}};
const rivals=[{id:'nova',name:'Nova',flag:'NO',skill:.77},{id:'atlas',name:'Atlas',flag:'DE',skill:.70},{id:'mira',name:'Mira',flag:'JP',skill:.62},{id:'roam',name:'Roam',flag:'BR',skill:.55}];
const $=id=>document.getElementById(id),screenIds=['home','game','result','final'];
let selectedMode='classic',selectedLevel='easy',match=[],roundIndex=0,guess=null,guessMap=null,resultMap=null,guessMarker=null,timerId=null,seconds=0,scores={you:0,nova:0,atlas:0,mira:0,roam:0},profile=loadProfile();
function show(id){screenIds.forEach(x=>$(x).classList.toggle('active',x===id))}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function key(){const configured=String(window.GEOSCOPE_CONFIG?.googleMapsApiKey||'').trim();if(configured)return configured;try{return localStorage.getItem('geoscopeGoogleEmbedKey')||''}catch(_){return''}}
function loadProfile(){try{return JSON.parse(localStorage.getItem('geoscopeProfile')||'null')||{xp:0,coins:0,wins:0}}catch(_){return{xp:0,coins:0,wins:0}}}
function saveProfile(){try{localStorage.setItem('geoscopeProfile',JSON.stringify(profile))}catch(_){}}
function leagueFor(xp){if(xp<1000)return{name:'Bronze III',short:'III',base:0,next:1000,c1:'#6f4e38',c2:'#bf8a5f'};if(xp<2500)return{name:'Silver II',short:'II',base:1000,next:2500,c1:'#68727b',c2:'#cbd1d5'};if(xp<5000)return{name:'Gold I',short:'I',base:2500,next:5000,c1:'#9a6812',c2:'#ffd66b'};if(xp<8000)return{name:'Platinum',short:'P',base:5000,next:8000,c1:'#2b7873',c2:'#75e1d5'};return{name:'Diamond',short:'D',base:8000,next:12000,c1:'#355e91',c2:'#8ac8ff'}}
function renderProfile(){const l=leagueFor(profile.xp),pct=Math.max(0,Math.min(100,(profile.xp-l.base)/(l.next-l.base)*100));$('leagueTop').textContent=l.name.toUpperCase();$('coinsTop').textContent=profile.coins.toLocaleString();$('leagueName').textContent=l.name;$('leagueBadge').textContent=l.short;$('leagueBadge').style.background=`linear-gradient(145deg,${l.c1},${l.c2})`;$('xpText').textContent=`${profile.xp.toLocaleString()} / ${l.next.toLocaleString()} XP`;$('xpFill').style.width=pct+'%'}
function participantData(){return[{id:'you',name:'You',flag:'YOU',skill:1},...rivals]}
function renderHomeRoster(){$('homeRoster').innerHTML=participantData().map((p,i)=>`<div class="player ${p.id==='you'?'you':''}"><div class="avatar">${p.flag}</div><div><b>${p.name}</b><small>${p.id==='you'?'CURRENT PLAYER':'AI RIVAL'}</small></div><strong>#${i+1}</strong></div>`).join('')}
function standings(){return participantData().map(p=>({...p,score:scores[p.id]||0})).sort((a,b)=>b.score-a.score)}
function renderMini(){$('miniBoard').innerHTML=standings().map((p,i)=>`<div class="minirow ${p.id==='you'?'me':''}"><span>${i+1}</span><span>${p.name}</span><b>${p.score.toLocaleString()}</b></div>`).join('')}
function renderStandingList(target){$(target).innerHTML=standings().map((p,i)=>`<div class="standing ${p.id==='you'?'me':''}"><b>${i+1}</b><span>${p.name}${p.id==='you'?' · YOU':' · AI'}</span><strong>${p.score.toLocaleString()}</strong></div>`).join('')}
function renderLevel(){const level=levels[selectedLevel];$('levelSummary').textContent=`${level.description} · ${level.reward.toFixed(level.reward%1?1:0)}× rewards`}
function mapUrl(loc){const q=new URLSearchParams({key:key(),location:`${loc.lat},${loc.lng}`,heading:String(loc.h||0),pitch:'0',fov:'90',radius:'120',source:'outdoor'});return'https://www.google.com/maps/embed/v1/streetview?'+q.toString()}
function startMatch(){if(!key()){$('ownerConfigNotice').hidden=false;return}const mode=modes[selectedMode],pool=locations.filter(x=>x.level===selectedLevel);if(pool.length<mode.rounds){alert('This level does not contain enough verified locations for the selected mode.');return}match=shuffle(pool).slice(0,mode.rounds);roundIndex=0;guess=null;scores={you:0,nova:0,atlas:0,mira:0,roam:0};show('game');startRound()}
function startRound(){clearInterval(timerId);guess=null;$('submitGuess').disabled=true;$('coords').textContent='Click anywhere on the map';$('guessPanel').classList.remove('open');if(guessMarker){guessMarker.remove();guessMarker=null}if(guessMap)guessMap.setView([20,0],2,{animate:false});const loc=match[roundIndex],mode=modes[selectedMode],level=levels[selectedLevel];$('roundLabel').textContent=`${level.name.toUpperCase()} · ${mode.name.toUpperCase()} · ROUND ${roundIndex+1} / ${match.length}`;$('streetView').src=mapUrl(loc);seconds=mode.seconds;updateTimer();timerId=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timerId);if(!guess)guess={lat:0,lng:0};finishRound(true)}},1000);renderMini()}
function updateTimer(){const m=Math.floor(seconds/60),s=seconds%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('timer').style.color=seconds<=10?'var(--red)':'var(--green)'}
function ensureGuessMap(){if(guessMap)return;if(!window.L){alert('The map library did not load. Refresh the page.');return}guessMap=L.map('guessMap',{worldCopyJump:true,minZoom:2}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(guessMap);guessMap.on('click',e=>{guess={lat:e.latlng.lat,lng:e.latlng.lng};if(guessMarker)guessMarker.remove();guessMarker=L.marker(e.latlng,{icon:pinIcon('guesspin')}).addTo(guessMap);$('coords').textContent=`${Math.abs(guess.lat).toFixed(2)}° ${guess.lat>=0?'N':'S'}, ${Math.abs(guess.lng).toFixed(2)}° ${guess.lng>=0?'E':'W'}`;$('submitGuess').disabled=false})}
function pinIcon(cls){return L.divIcon({className:cls,html:'<span class="pinshape"></span>',iconSize:[26,32],iconAnchor:[13,30]})}
function openMap(){ensureGuessMap();if(!guessMap)return;$('guessPanel').classList.add('open');setTimeout(()=>guessMap.invalidateSize(),240)}
function distance(a,b,c,d){const r=x=>x*Math.PI/180,R=6371,dy=r(c-a),dx=r(d-b),h=Math.sin(dy/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dx/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function scoreFor(km){return Math.max(0,Math.round(5000*Math.exp(-km/1900)))}
function finishRound(timeout){if(!guess)return;clearInterval(timerId);const loc=match[roundIndex],km=distance(guess.lat,guess.lng,loc.lat,loc.lng),userScore=scoreFor(km);scores.you+=userScore;const penalty={easy:0,medium:120,hard:250}[selectedLevel];rivals.forEach(p=>{const base=2100+p.skill*2300-penalty,variance=(Math.random()-.5)*1900,bonus=selectedMode==='duel'?250:0;scores[p.id]+=Math.max(150,Math.min(5000,Math.round(base+variance+bonus)))});$('roundScore').innerHTML=`${userScore.toLocaleString()} <span>/ 5,000</span>`;$('answerPlace').textContent=`${loc.city}, ${loc.country}`;$('answerDistance').textContent=`${Math.round(km).toLocaleString()} km away · ${levels[selectedLevel].name}${timeout?' · time expired':''}`;$('resultTitle').textContent=userScore>4200?'Excellent read.':userScore>2800?'Strong guess.':userScore>1400?'You found the region.':'The world is difficult.';show('result');renderResultMap(loc);renderStandingList('roundStandings')}
function renderResultMap(loc){if(resultMap){resultMap.remove();resultMap=null}resultMap=L.map('resultMap',{zoomControl:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(resultMap);const a=L.latLng(loc.lat,loc.lng),g=L.latLng(guess.lat,guess.lng);L.marker(a,{icon:pinIcon('actualpin')}).addTo(resultMap);L.marker(g,{icon:pinIcon('guesspin')}).addTo(resultMap);L.polyline([a,g],{color:'#c8ff43',weight:3,dashArray:'8 10'}).addTo(resultMap);resultMap.fitBounds(L.latLngBounds(a,g).pad(.35),{maxZoom:7});setTimeout(()=>resultMap.invalidateSize(),100)}
function nextRound(){roundIndex++;if(roundIndex>=match.length){finishMatch();return}show('game');startRound()}
function finishMatch(){const board=standings(),rank=board.findIndex(p=>p.id==='you')+1,total=scores.you,multiplier=levels[selectedLevel].reward,xp=Math.round((total/55+(6-rank)*40+(selectedMode==='duel'?120:0))*multiplier),coins=Math.round((total/300+(6-rank)*8)*multiplier);profile.xp+=xp;profile.coins+=coins;if(rank===1)profile.wins++;saveProfile();$('finishPlace').textContent=`${rank}${rank===1?'ST':rank===2?'ND':rank===3?'RD':'TH'} PLACE · ${levels[selectedLevel].name.toUpperCase()}`;$('totalScore').textContent=total.toLocaleString();$('xpReward').textContent='+'+xp.toLocaleString();$('coinReward').textContent='+'+coins.toLocaleString();$('badgeReward').textContent=rank===1?'★':'◆';renderStandingList('finalBoard');renderProfile();show('final')}
$('modes').addEventListener('click',e=>{const btn=e.target.closest('.mode');if(!btn)return;selectedMode=btn.dataset.mode;document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x===btn))});
$('levels').addEventListener('click',e=>{const btn=e.target.closest('.level');if(!btn)return;selectedLevel=btn.dataset.level;document.querySelectorAll('.level').forEach(x=>x.classList.toggle('active',x===btn));renderLevel()});
$('startBtn').addEventListener('click',startMatch);$('againBtn').addEventListener('click',startMatch);$('homeBtn').addEventListener('click',()=>show('home'));$('mapTrigger').addEventListener('click',openMap);$('closeMap').addEventListener('click',()=>$('guessPanel').classList.remove('open'));$('submitGuess').addEventListener('click',()=>finishRound(false));$('nextRound').addEventListener('click',nextRound);
renderProfile();renderHomeRoster();renderLevel();
})();
